### ISSUE TITLE
Resizing claim corrupts and error deleting corrupted claim

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#114]
There was a problem with resizing a claim, it evidently didnt resize properly and now the claim is corrupted.
Using a stick with shift right click shows the new claim borders but the old claim is still there.
If you right click with the stick, even though shift right click shows borders, it says that nobody owns the block.

The new claim borders not actually protect anything, even though there is an outline.

When attempting to remove the claim completely, it says "Error occured while executing command: null"

```
[08:15:19] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'abandonclaim' for source EntityPlayerMP['BTC'/7864, l='world', x=5806.91, y=64.00, z=2992.30]: null
java.lang.NullPointerException
        at me.ryanhamshire.griefprevention.DataStore.deleteClaim(DataStore.java:399) ~[DataStore.class:?]
        at me.ryanhamshire.griefprevention.command.CommandClaimAbandon.execute(CommandClaimAbandon.java:81) ~[CommandClaimAbandon.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:331) ~[CommandSpec.class:1.8.9-1890-4.2.0-BETA-1595]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1595]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279) [SpongeCommandManager.class:1.8.9-1890-4.2.0-BETA-1595]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1595]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by inklit** [comment]
When the server is restarted, the corrupted claim returns to normal and it's size is what it was supposed to be resized to.

**Comment by bloodmc** [comment]
@inklit You need to be more specific... What build are you using? What claim type? Does this happen to newly created claims? Zip your ClaimData folder and let me know the location so I can test on my end.

**Comment by inklit** [comment]
I am using the latest build (43). 
It seems I'm unable to reproduce this after I restarted the server, it seems to have been a temporary problem.
The claim type is a standard claim, at the time the claim was newly created.
http://66.11.122.190/ClaimData.zip is the ZIP file containg the ClaimData.
The location of the claim that was corrupted (but apparently is not anymore after a server restart) is at 
5797, 74, 2994.

**Comment by bloodmc** [comment]
@inklit OK I'll keep this ticket open in case it happens again. Let me know if the problem can be reproduced.

**Comment by inklit** [comment]
This looks like it has happened again on my server.
I still can't seem to figure out *why* it happens, but here's the errors that showed up when the player tried to delete their corrupted claim.
Unfortunately these are as much as I can provide to attempt to fix this problem, though they probably are not very useful.

```
[00:38:24] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'abandonclaim' for source EntityPlayerMP['Cloud_Ninja'/758, l='world', x=2688.86, y=63.00, z=3842.02]: null
java.lang.NullPointerException
        at me.ryanhamshire.griefprevention.DataStore.deleteClaim(DataStore.java:399) ~[DataStore.class:?]
        at me.ryanhamshire.griefprevention.command.CommandClaimAbandon.execute(CommandClaimAbandon.java:81) ~[CommandClaimAbandon.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:331) ~[CommandSpec.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279) [SpongeCommandManager.class:1.8.9-1890-4.2.0-BETA-1625]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1625]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[00:38:28] [Server thread/INFO] [io.github.hsyyid.essentialcmds]: [Cloud_Ninja] executed command abandonclaim
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]: java.nio.file.NoSuchFileException: ./world/GriefPreventionData/ClaimData/b2c87065-9cc9-4f9f-908f-85626224cb50
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at java.nio.file.Files.delete(Files.java:1126)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at me.ryanhamshire.griefprevention.FlatFileDataStore.deleteClaimFromSecondaryStorage(FlatFileDataStore.java:46
4)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at me.ryanhamshire.griefprevention.DataStore.deleteClaim(DataStore.java:393)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at me.ryanhamshire.griefprevention.command.CommandClaimAbandon.execute(CommandClaimAbandon.java:81)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:331)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.util.Util.func_181617_a(SourceFile:44)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
[00:38:28] [Server thread/INFO] [STDERR]: [me.ryanhamshire.griefprevention.FlatFileDataStore:deleteClaimFromSecondaryStorage:466]:      at java.lang.Thread.run(Thread.java:745)
[00:38:28] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'abandonclaim' for source EntityPlayerMP['Cloud_Ninja'/758, l='world', x=2692.56, y=63.00, z=3843.53]: null
java.lang.NullPointerException
        at me.ryanhamshire.griefprevention.DataStore.deleteClaim(DataStore.java:399) ~[DataStore.class:?]
        at me.ryanhamshire.griefprevention.command.CommandClaimAbandon.execute(CommandClaimAbandon.java:81) ~[CommandClaimAbandon.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:331) ~[CommandSpec.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279) [SpongeCommandManager.class:1.8.9-1890-4.2.0-BETA-1625]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1625]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[00:38:35] [Server thread/INFO]: [Member] Cloud_Ninja: um
[00:38:36] [Server thread/INFO]: [Member] Cloud_Ninja: btc
[00:38:38] [Server thread/INFO]: [Administrator] BTC: ?
[00:38:38] [Server thread/INFO]: [Member] Cloud_Ninja: I think GP is borked
```
