### ISSUE TITLE
Plethora mod issues with protection

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#123]
Plethora is a peripheral mod for ComputerCraft, and lasers shot by a computer's Item Manipulator are able to break blocks in protected areas and parts of the world that the player who placed the Manipulator is not trusted in.

Lasers shot by players themselves are protected and have no issues, only when they are shot from an Item Manipulator is there a problem.

**NullPointerException in ChangeBlockEvent** 
When the mod attempts to fire a laser, this error is thrown.

```
[14:05:33] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Pre$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@7a13a43f
java.lang.NullPointerException
        at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:1005) ~[lf.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.sendMessage(EntityPlayerMP.java:54) ~[lf.class:?]
        at me.ryanhamshire.griefprevention.GriefPrevention.sendMessage(GriefPrevention.java:1007) ~[GriefPrevention.class:?]
        at me.ryanhamshire.griefprevention.event.BlockEventHandler.onBlockPre(BlockEventHandler.java:137) ~[BlockEventHandler.class:?]
        at org.spongepowered.common.event.listener.PreListener_BlockEventHandler_onBlockPre62.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:242) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1625]
        at net.minecraft.server.dedicated.DedicatedServer.func_175579_a(DedicatedServer.java:110) [ko.class:?]
        at net.minecraft.world.WorldServer.canMineBlockBody(WorldServer.java:758) [le.class:?]
        at net.minecraft.world.WorldProvider.canMineBlock(WorldProvider.java:487) [anm.class:?]
        at net.minecraft.world.World.func_175660_a(World.java:3391) [adm.class:?]
        at net.minecraft.world.WorldServer.func_175660_a(WorldServer.java:754) [le.class:?]
        at org.squiddev.plethora.gameplay.modules.EntityLaser.onImpact(EntityLaser.java:219) [EntityLaser.class:?]
        at org.squiddev.plethora.gameplay.modules.EntityLaser.func_70071_h_(EntityLaser.java:193) [EntityLaser.class:?]
        at net.minecraft.world.World.redirect$onCallEntityUpdate$0(World.java:1247) [adm.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1862) [adm.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700) [le.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1831) [adm.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:663) [le.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**GameProfile lookup spam**
While I'm aware that this is an issue with Sponge and not GriefPrevention, I would like to point out the existence of this bug here because it could be relevent.

The FakePlayer that Plethora creates spams the console infinitely with this error message.
There is already a bug report open in Sponge related to GameProfile lookup spam for FakePlayers, so I will post this information there as well.
If this information is irrelevent, simply ignore it.

```
[14:05:37] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@7169b6fd[id=ebcda071-3ef5-4f4a-849d-c078264010c4,name=,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
        at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
        at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
        at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1625]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by bloodmc** [comment]
@inklit It is your job to mark these "FakePlayers" as invalid in sponge's config. There is a section just for that. As for NPE, I'll add a fix for that.

**Comment by inklit** [comment]
@bloodmc 
I have already marked it as invalid in Sponge's configuration, for some reason it seems to impose a lack of quotes which I think is the problem.
````
        invalid-lookup-uuids=[
            "00000000-0000-0000-0000-000000000000",
            "0d0c4ca0-4ff1-11e4-916c-0800200c9a66",
            "41c82c87-7afb-4024-ba57-13d2c99cae77",
            ebcda071-3ef5-4f4a-849d-c078264010c4
        ]
```
when it should really be
```
        invalid-lookup-uuids=[
            "00000000-0000-0000-0000-000000000000",
            "0d0c4ca0-4ff1-11e4-916c-0800200c9a66",
            "41c82c87-7afb-4024-ba57-13d2c99cae77",
            "ebcda071-3ef5-4f4a-849d-c078264010c4"
        ]
```
In any case, the `invalid-lookup-uuids` option does not work. 
This isn't exactly the place to discuss this but I thought I'd let you know.
