### ISSUE TITLE
Could not pass ChangeBlockEvent$Pre$Impl NullPointerException

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#141]
Not entirely sure why this error happens, though it somehow is related to Iron Chests mod.

```
[15:15:52] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Pre$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@434df449
java.lang.NullPointerException
        at me.ryanhamshire.griefprevention.claim.Claim.getOwnerUniqueId(Claim.java:157) ~[Claim.class:?]
        at me.ryanhamshire.griefprevention.event.BlockEventHandler.onBlockPre(BlockEventHandler.java:108) ~[BlockEventHandler.class:?]
        at org.spongepowered.common.event.listener.PreListener_BlockEventHandler_onBlockPre61.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1666]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:242) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1666]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1666]
        at org.spongepowered.common.event.SpongeCommonEventFactory.handleChangeBlockEventPre(SpongeCommonEventFactory.java:581) [SpongeCommonEventFactory.class:1.8.9-1890-4.2.0-BETA-1666]
        at net.minecraft.world.WorldServer.handler$addBlockEvent$0(WorldServer.java:542) [le.class:?]
        at net.minecraft.world.WorldServer.func_175641_c(WorldServer.java) [le.class:?]
        at cpw.mods.ironchest.TileEntityIronChest.func_73660_a(TileEntityIronChest.java:332) [TileEntityIronChest.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:730) [le.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

```

Using latest build as of this post.

**Comment by FiveEYZ** [comment]
so im getting a insane spam in console: http://pastebin.com/raw/Tzv8xkkm

after 20 minutes server uptime the `fml-server-latest.log` is already at 44879kb

**Comment by FiveEYZ** [comment]
turned out that GP didnt create a Wilderness claim, fixed the spam by creating 1 manually

**Comment by bloodmc** [comment]
This is resolved in latest builds.
