### ISSUE TITLE
Error feedback: cannot stop explode from some mods

### ISSUE THREAD

**Issue by 5igm** [MinecraftPortCentral/GriefPrevention#145]
spongeforge-1.10.2-2052-5.0.0-BETA-1679
griefprevention-1.10.2-2.1.0.67

```
[22:58:41] [Server thread/ERROR] [Sponge/]: Could not pass Detonate to Plugin{id=griefprevention, name=GriefPrevention, version=2.1.0, description=This plugin is designed to prevent all forms of grief., source=E:\sponge-1.10.2\mods\griefprevention-1.10.2-2.1.0.67.jar}
java.lang.NullPointerException
    at me.ryanhamshire.griefprevention.GPPermissionHandler.getClaimPermission(GPPermissionHandler.java:65) ~[GPPermissionHandler.class:?]
    at me.ryanhamshire.griefprevention.event.BlockEventHandler.onExplosion(BlockEventHandler.java:302) ~[BlockEventHandler.class:?]
    at org.spongepowered.common.event.listener.DetonateListener_BlockEventHandler_onExplosion120.handle(Unknown Source) ~[?:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2052-5.0.0-BETA-1679]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:111) [EventBus.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:100) [EventBus.class:?]
    at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:452) [ForgeEventFactory.class:?]
    at net.minecraft.world.Explosion.func_77278_a(Explosion.java:133) [ahy.class:?]
    at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1174) [ls.class:?]
    at net.minecraft.world.World.func_72876_a(World.java:2303) [aid.class:?]
    at net.unladenswallow.minecraft.quiver.entity.EntityExplodingArrow.handleInTileState(EntityExplodingArrow.java:28) [EntityExplodingArrow.class:?]
    at net.unladenswallow.minecraft.quiver.entity.EntityCustomArrow.func_70071_h_(EntityCustomArrow.java:124) [EntityCustomArrow.class:?]
    at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:145) [TrackingUtil.class:1.10.2-2052-5.0.0-BETA-1679]
    at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$0(WorldServer.java:1141) [ls.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:1964) [aid.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) [ls.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1260) [aid.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) [ls.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by bloodmc** [comment]
@5igm Does this happen with latest 1.10.2 or 1.11 builds?
