### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by 5igm** [MinecraftPortCentral/GriefPrevention#152]
```
[03:56:26] [Server thread/ERROR] [Sponge/]: Could not pass SpawnEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.1.0, description=This plugin is designed to prevent all forms of grief., source=E:\sponge-1.10.2\mods\griefprevention-1.10.2-2.1.0.67.jar}
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(Unknown Source) ~[?:1.8.0_101]
	at java.util.AbstractList$Itr.remove(Unknown Source) ~[?:1.8.0_101]
	at org.spongepowered.api.event.entity.AffectEntityEvent.filterEntities(AffectEntityEvent.java:101) ~[AffectEntityEvent.class:1.10.2-2052-5.0.0-BETA-1679]
	at me.ryanhamshire.griefprevention.event.EntityEventHandler.onEntitySpawn(EntityEventHandler.java:175) ~[EntityEventHandler.class:?]
	at org.spongepowered.common.event.listener.SpawnEntityEventListener_EntityEventHandler_onEntitySpawn161.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:332) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:377) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:362) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) [SpongeImpl.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.common.event.tracking.phase.TrackingPhase.spawnEntityOrCapture(TrackingPhase.java:290) [TrackingPhase.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.common.event.tracking.CauseTracker.spawnEntity(CauseTracker.java:497) [CauseTracker.class:1.10.2-2052-5.0.0-BETA-1679]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:983) [ls.class:?]
	at lellson.roughMobs.events.ZombieEvents.setHorse(ZombieEvents.java:177) [ZombieEvents.class:?]
	at lellson.roughMobs.events.ZombieEvents.onWorldJoin(ZombieEvents.java:161) [ZombieEvents.class:?]
	at lellson.roughMobs.events.ZombieEvents.onWorldJoin(ZombieEvents.java:33) [ZombieEvents.class:?]
	at lellson.roughMobs.events.DefaultEvents.eventJoinWorld(DefaultEvents.java:85) [DefaultEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_75_DefaultEvents_eventJoinWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:131) [EventBus.class:?]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callEntityJoinWorldEvent(SpongeForgeEventFactory.java:979) [SpongeForgeEventFactory.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:425) [SpongeForgeEventFactory.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:325) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:377) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:362) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) [SpongeImpl.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.common.event.tracking.phase.GenerationPhase$GeneralGenerationPhaseState.unwind(GenerationPhase.java:167) [GenerationPhase$GeneralGenerationPhaseState.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.common.event.tracking.phase.GenerationPhase.unwind(GenerationPhase.java:239) [GenerationPhase.class:1.10.2-2052-5.0.0-BETA-1679]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:185) [CauseTracker.class:1.10.2-2052-5.0.0-BETA-1679]
	at net.minecraft.world.WorldEntitySpawner.handler$onFindChunksForSpawningReturn$0(WorldEntitySpawner.java:115) [aik.class:?]
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:183) [aik.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by bloodmc** [comment]
This is a Sponge bug.

https://github.com/SpongePowered/SpongeCommon/issues/896
