### ISSUE TITLE
java.lang.Error crash

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#174]
Don't know why it happened, I wasn't on when the server crashed.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1755.jar)
  TransformerLoader (OpenComputers-MC1.8.9-1.6.0.8-rc.1.jar)
  TweaksLoadingPlugin (CCTweaks-1.8.9-1.0.1-patched-02.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 10/2/16 2:42 PM
Description: Watching Server

java.lang.Error
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.RuntimeException.<init>(RuntimeException.java:51)
	at java.lang.NullPointerException.<init>(NullPointerException.java:60)
	at me.ryanhamshire.griefprevention.claim.Claim.getOwnerUniqueId(Claim.java:157)
	at me.ryanhamshire.griefprevention.event.BlockEventHandler.onBlockNotify(BlockEventHandler.java:177)
	at org.spongepowered.common.event.listener.NotifyNeighborBlockEventListener_BlockEventHandler_onBlockNotify60.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:184)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callNotifyNeighborEvent(SpongeCommonEventFactory.java:623)
	at net.minecraft.world.World.func_175695_a(World.java:1372)
	at dan200.computercraft.shared.util.RedstoneUtil.propogateRedstoneOutput(RedstoneUtil.java:90)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateOutput(TileComputerBase.java:344)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_73660_a(TileComputerBase.java:214)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:736)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.RuntimeException.<init>(RuntimeException.java:51)
	at java.lang.NullPointerException.<init>(NullPointerException.java:60)
	at me.ryanhamshire.griefprevention.claim.Claim.getOwnerUniqueId(Claim.java:157)
	at me.ryanhamshire.griefprevention.event.BlockEventHandler.onBlockNotify(BlockEventHandler.java:177)
	at org.spongepowered.common.event.listener.NotifyNeighborBlockEventListener_BlockEventHandler_onBlockNotify60.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:184)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callNotifyNeighborEvent(SpongeCommonEventFactory.java:623)
	at net.minecraft.world.World.func_175695_a(World.java:1372)
	at dan200.computercraft.shared.util.RedstoneUtil.propogateRedstoneOutput(RedstoneUtil.java:90)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateOutput(TileComputerBase.java:344)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_73660_a(TileComputerBase.java:214)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:736)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)

-- Thread Dump --
//omitted, its huge... if you need it let me know

Stacktrace:
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:63)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 2.6.32-46-pve
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 573719296 bytes (547 MB) / 1610674176 bytes (1536 MB) up to 8563785728 bytes (8167 MB)
	JVM Flags: 4 total; -Xmx8192M -Xincgc -XX:ParallelGCThreads=3 -XX:MaxPermSize=128m
	IntCache: cache: 11, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.8-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	sponge{1.8.9-1890-4.2.0-BETA-1755} [SpongeForge] (spongeforge-1.8.9-1890-4.2.0-BETA-1755.jar) 
	UCHIJAAAA	<CCTweaks ASM>{1.0.1} [<CCTweaks ASM>] (minecraft.jar) 
	UCHIJAAAA	io.github.hsyyid.adminshop{1.8.1} [AdminShop] (AdminShop-1.8.9-1.8.1-universal.jar) 
	UCHIJAAAA	ComputerCraft{1.79} [ComputerCraft] (ComputerCraft1.79.jar) 
	UCHIJAAAA	CCTweaks{1.0.1} [CCTweaks] (CCTweaks-1.8.9-1.0.1-patched-02.jar) 
	UCHIJAAAA	chunkloaderz{1.0.3} [ChunkLoaderZ] (ChunkLoaderZ-1.8.9-1.0.3.jar) 
	UCHIJAAAA	Dynmap{2.3-15} [Dynmap] (Dynmap-2.3-forge-1.8.9.jar) 
	UCHIJAAAA	io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds] (EssentialCmds-1.8.9-8.1.14-universal.jar) 
	UCHIJAAAA	griefprevention{2.0.0} [GriefPrevention] (griefprevention-1.8.9-2.0.0.70.jar) 
	UCHIJAAAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAAAA	JEI{2.28.9.176} [Just Enough Items] (jei_1.8.9-2.28.9.176.jar) 
	UCHIJAAAA	io.github.hsyyid.kits{1.7.4} [Kits] (Kits-1.7.4.jar) 
	UCHIJAAAA	voterestart{1.0} [Vote Restart] (liggy_voterestart.jar) 
	UCHIJAAAA	logdupepatch{1.0} [LogDupePatch] (logdupepatch-2.0-snapshot.jar) 
	UCHIJAAAA	minimalperipherals{0.0} [MinimalPeripherals] (MinimalPeripherals-lite-1.8.9-1.1.jar) 
	UCHIJAAAA	MoreFurnaces{1.5.2} [More Furnaces] (MoreFurnaces-1.8.9-1.5.2.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.8-rc.1} [OpenComputers] (OpenComputers-MC1.8.9-1.6.0.8-rc.1.jar) 
	UCHIJAAAA	ninja.leaping.permissionsex{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	totaleconomy{1.4.1} [Total Economy] (TotalEconomy-v1.4.1.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1-dist.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1755.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
TransformerLoader (OpenComputers-MC1.8.9-1.6.0.8-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
TweaksLoadingPlugin (CCTweaks-1.8.9-1.0.1-patched-02.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 50; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by bloodmc** [comment]
This has nothing to do with GP...Your server timed out and that was the last thing it was doing.
