### ISSUE TITLE
Some claims not loading with migration from 1.8.9->1.10.2

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#206]
## Versions
Using `forge-1.10.2-12.18.2.2123-universal`, `spongeforge-1.10.2-2123-6.0.0-BETA-1876`, and `griefprevention-1.10.2-2.1.0.129`.

## Problem
When I updated my server from 1.8.9 to 1.10.2, I noticed that a ton of claims were missing from the areas near spawn.
I figured out very quickly that GriefPrevention has failed to load over 50 claims with this error message.

The error will repeat for every UUID that does not load.
```
[19:00:52] [Server thread/ERROR] [Sponge/]: Failed to load configuration
org.spongepowered.api.data.persistence.InvalidDataException: Could not deserialize something correctly, likely due to bad type data.
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:88) ~[AbstractDataBuilder.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.common.data.SpongeDataManager.deserialize(SpongeDataManager.java:223) ~[SpongeDataManager.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.deserialize(TextConfigSerializer.java:79) ~[TextConfigSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.deserialize(TextConfigSerializer.java:57) ~[TextConfigSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:85) ~[spongeforge-1.10.2-2123-6.0.0-BETA-1876.jar:1.10.2-2123-6.0.0-BETA-1876]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:148) ~[spongeforge-1.10.2-2123-6.0.0-BETA-1876.jar:1.10.2-2123-6.0.0-BETA-1876]
	at me.ryanhamshire.griefprevention.configuration.ClaimStorageData.reload(ClaimStorageData.java:149) [ClaimStorageData.class:?]
	at me.ryanhamshire.griefprevention.configuration.ClaimStorageData.<init>(ClaimStorageData.java:111) [ClaimStorageData.class:?]
	at me.ryanhamshire.griefprevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:345) [FlatFileDataStore.class:?]
	at me.ryanhamshire.griefprevention.FlatFileDataStore.loadClaimData(FlatFileDataStore.java:288) [FlatFileDataStore.class:?]
	at me.ryanhamshire.griefprevention.FlatFileDataStore.loadWorldData(FlatFileDataStore.java:183) [FlatFileDataStore.class:?]
	at me.ryanhamshire.griefprevention.event.WorldEventHandler.onWorldLoad(WorldEventHandler.java:40) [WorldEventHandler.class:?]
	at org.spongepowered.common.event.listener.LoadWorldEventListener_WorldEventHandler_onWorldLoad100.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:340) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) [SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:140) [SpongeImpl.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:813) [WorldManager.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:755) [WorldManager.class:1.10.2-2123-6.0.0-BETA-1876]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:324) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: org.spongepowered.api.data.persistence.InvalidDataException: org.spongepowered.api.text.serializer.TextParseException: Failed to parse JSON
	at org.spongepowered.api.text.serializer.TextConfigSerializer.buildContent(TextConfigSerializer.java:101) ~[TextConfigSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:86) ~[AbstractDataBuilder.class:1.10.2-2123-6.0.0-BETA-1876]
	... 24 more
Caused by: org.spongepowered.api.text.serializer.TextParseException: Failed to parse JSON
	at org.spongepowered.common.text.serializer.JsonTextSerializer.deserialize(JsonTextSerializer.java:50) ~[JsonTextSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.lambda$buildContent$2(TextConfigSerializer.java:99) ~[TextConfigSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_91]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.buildContent(TextConfigSerializer.java:99) ~[TextConfigSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:86) ~[AbstractDataBuilder.class:1.10.2-2123-6.0.0-BETA-1876]
	... 24 more
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2
	at com.google.gson.internal.Streams.parse(Streams.java:56) ~[Streams.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:501) ~[og.class:?]
	at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:512) ~[og.class:?]
	at net.minecraft.util.text.ITextComponent$Serializer.func_150699_a(ITextComponent.java:260) ~[ey$a.class:?]
	at org.spongepowered.common.text.serializer.JsonTextSerializer.deserialize(JsonTextSerializer.java:48) ~[JsonTextSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.lambda$buildContent$2(TextConfigSerializer.java:99) ~[TextConfigSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_91]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.buildContent(TextConfigSerializer.java:99) ~[TextConfigSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:86) ~[AbstractDataBuilder.class:1.10.2-2123-6.0.0-BETA-1876]
	... 24 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:560) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.internal.Streams.parse(Streams.java:42) ~[Streams.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:501) ~[og.class:?]
	at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:512) ~[og.class:?]
	at net.minecraft.util.text.ITextComponent$Serializer.func_150699_a(ITextComponent.java:260) ~[ey$a.class:?]
	at org.spongepowered.common.text.serializer.JsonTextSerializer.deserialize(JsonTextSerializer.java:48) ~[JsonTextSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.lambda$buildContent$2(TextConfigSerializer.java:99) ~[TextConfigSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_91]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.buildContent(TextConfigSerializer.java:99) ~[TextConfigSerializer.class:1.10.2-2123-6.0.0-BETA-1876]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:86) ~[AbstractDataBuilder.class:1.10.2-2123-6.0.0-BETA-1876]
	... 24 more
[19:00:52] [Server thread/INFO] [griefprevention/]: GriefPrevention: ff2dac7a-f6b2-4765-9a2e-d2f24a0074c3 java.lang.NullPointerException
	at me.ryanhamshire.griefprevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:347)
	at me.ryanhamshire.griefprevention.FlatFileDataStore.loadClaimData(FlatFileDataStore.java:288)
	at me.ryanhamshire.griefprevention.FlatFileDataStore.loadWorldData(FlatFileDataStore.java:183)
	at me.ryanhamshire.griefprevention.event.WorldEventHandler.onWorldLoad(WorldEventHandler.java:40)
	at org.spongepowered.common.event.listener.LoadWorldEventListener_WorldEventHandler_onWorldLoad100.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:340)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:140)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:813)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:755)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:324)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)
```

## Additional Information
Here is the contents of the file in `/world/GriefPreventionData/ClaimData/ff2dac7a-f6b2-4765-9a2e-d2f24a0074c3` for an example of one that does not load.
```
# 2.0.0
# # If you need help with the configuration or have any questions related to GriefPrevention,
# # join us at the IRC or drop by our forums and leave a post.
# # IRC: #griefprevention @ irc.esper.net ( http://webchat.esper.net/?channel=griefprevention )
# # Forums: https://forums.spongepowered.org/t/griefprevention-official-thread-1-8-9-1-10-2/1123/
# 

GriefPrevention {
    accessors=[]
    builders=[
        "679b95a2-6b49-4a2b-8eda-8d081e7f7781"
    ]
    claim-farewell=ByeBye
    claim-greeting {
        extra=[
            {
                color="dark_gray"
                text="Welcome_to_"
            },
            {
                color="dark_aqua"
                text="Beast's_"
            },
            {
                color="dark_green"
                text="House."
            }
        ]
        text=""
    }
    claim-name=House
    claim-type=BASIC
    coowners=[]
    cuboid=false
    date-created="2016-10-22T18:52:18.083Z"
    date-last-active="2016-10-24T20:16:40.876Z"
    greater-boundary-corner="6165;60;3886"
    lesser-boundary-corner="6140;43;3866"
    managers=[]
    owner-uuid="7f793eeb-6010-43bb-9724-2148edf791b3"
    subdivisions {}
    world-uuid="53197de6-7334-4eb5-bb3f-0594827b00bb"
}
```

I've found that a lot of claims do load, out of the 726 claims on my server about 50-60 of them do not load.
Unfortunately, most of the claims which do not load are incredibly important claims around spawn and the surrounding area. These claims are likely very old claims since they were created in my server's infancy.
It seems that some newer claims have also broken too though.

**Comment by inklit** [comment]
It seems removing these lines from the file fix the corruption - but this is a long and tedious process with 60 claims and I don't know if it will happen again.

```
    claim-farewell=ByeBye
    claim-name=House
```

**Comment by bloodmc** [comment]
@inklit this was actually a configurate bug which was patched in Sponge API then recently removed. Try removing the header to see if that solves the issue.

**Comment by inklit** [comment]
Odd. I tried removing the header and it does not seem to have any affect. However, removing any instance of `claim-farewell`, `claim-greeting`, and `claim-name` allows it to load again. I'll try removing the header again.

**Comment by bloodmc** [comment]
Ah yes Text serialization was changed in 1.9+ in SpongeAPI. I'll see if I can come up with a migration tool but don't count on it anytime soon.

**Comment by inklit** [comment]
I've found that the easiest way to deal with this problem is to simply delete lines that contain `claim-farewell=`, `claim-greeting=`, and `claim-name=`. The = is important, because properly serialized text will use brackets instead of =, so you'll only be deleting lines that are not supported anymore. 

Surprisingly enough, there is content in my files that is properly serialized already, so it won't be deleting *everything*.

**Comment by bloodmc** [comment]
Great thanks!
