### ISSUE TITLE
[Crash] Creating claims via. API sometimes causes a crash due to WatchDog

### ISSUE THREAD

**Issue by Slind14** [MinecraftPortCentral/GriefPrevention#317]
Version: 2.3.1.255

This is most certainly not GP's fault, but I thought I should report it anyway, as it is affecting GP:

```-- Head --
Thread: Server Watchdog
Stacktrace:
java.lang.Error
    at java.util.HashMap$TreeNode.balanceInsertion(HashMap.java:2257)
    at java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2007)
    at java.util.HashMap.putVal(HashMap.java:637)
    at java.util.HashMap.put(HashMap.java:611)
    at java.util.HashSet.add(HashSet.java:219)
    at me.ryanhamshire.griefprevention.claim.GPClaim.getChunkHashes(GPClaim.java:1128)
    at me.ryanhamshire.griefprevention.claim.GPClaim.doesClaimOverlap(GPClaim.java:1320)
    at me.ryanhamshire.griefprevention.claim.GPClaim$ClaimBuilder.build(GPClaim.java:1982)
    at net.mohron.skyclaims.util.IslandUtil.createProtection(IslandUtil.java:131)
```

```-- Head --
Thread: Server Watchdog
Stacktrace:
java.lang.Error
    at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.containsKey(Long2ObjectOpenHashMap.java:394)
    at it.unimi.dsi.fastutil.longs.AbstractLong2ObjectFunction.get(AbstractLong2ObjectFunction.java:124)
    at me.ryanhamshire.griefprevention.claim.GPClaimManager.addClaim(GPClaimManager.java:222)
    at me.ryanhamshire.griefprevention.claim.GPClaimManager.addClaim(GPClaimManager.java:173)
```

**Comment by bloodmc** [comment]
Let me know if this happens with latest builds.

**Comment by bloodmc** [comment]
Closing as I have not heard any other users report this issue.
