### ISSUE TITLE
Entity events console spam

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#342]
Using 
spongeforge-1.10.2-2221-5.2.0-BETA-2219.jar
griefprevention-1.10.2-2.3.1.267.jar
LuckPerms-Sponge-3.0.12.jar
on test modpack, console is spammed with errors like this one:
```
[14:27:15] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.267.jar}
java.lang.ArrayIndexOutOfBoundsException: 1
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getPermissionIdentifier(GPPermissionHandler.java:322) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getPermissionIdentifier(GPPermissionHandler.java:291) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getClaimPermission(GPPermissionHandler.java:81) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getClaimPermission(GPPermissionHandler.java:65) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.listener.EntityEventHandler.onEntityMove(EntityEventHandler.java:668) ~[EntityEventHandler.class:?]
>       at org.spongepowered.common.event.listener.MoveEntityEventListener_EntityEventHandler_onEntityMove171.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.fireMovementEvents(EntityTickPhaseState.java:307) [EntityTickPhaseState.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.processPostTick(EntityTickPhaseState.java:280) [EntityTickPhaseState.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:68) [TickPhase.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:251) [CauseTracker.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:161) [TrackingUtil.class:1.10.2-2221-5.2.0-BETA-2219]
>       at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjn000(WorldServer.java:2810) [ls.class:?]
>       at net.minecraft.world.World.func_72866_a(World.java:4071) [aid.class:?]
>       at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
>       at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
>       at net.minecraft.world.World.func_72939_s(World.java:5954) [aid.class:?]
>       at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2153) [ls.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

and this one

```
[14:29:55] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.267.jar}
java.lang.ArrayIndexOutOfBoundsException: 1
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getPermissionIdentifier(GPPermissionHandler.java:322) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getPermissionIdentifier(GPPermissionHandler.java:291) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getClaimPermission(GPPermissionHandler.java:81) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getClaimPermission(GPPermissionHandler.java:65) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.listener.EntityEventHandler.onEntityMove(EntityEventHandler.java:668) ~[EntityEventHandler.class:?]
>       at org.spongepowered.common.event.listener.MoveEntityEventListener_EntityEventHandler_onEntityMove171.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.fireMovementEvents(EntityTickPhaseState.java:307) [EntityTickPhaseState.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.processPostTick(EntityTickPhaseState.java:280) [EntityTickPhaseState.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:68) [TickPhase.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:251) [CauseTracker.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:161) [TrackingUtil.class:1.10.2-2221-5.2.0-BETA-2219]
>       at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjn000(WorldServer.java:2810) [ls.class:?]
>       at net.minecraft.world.World.func_72866_a(World.java:4071) [aid.class:?]
>       at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
>       at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
>       at net.minecraft.world.World.func_72939_s(World.java:5954) [aid.class:?]
>       at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2153) [ls.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Mods list:
```
AbyssalCraft-1.10.2-1.9.3.10.jar
AquaCreepers-1.2.1.jar
ArsMagica2-1.10.2-1.5.0-17b.jar
AutoRegLib-1.0-2.jar
Baubles-1.10.2-1.3.9.jar
baublesstuff-3.0.2.jar
BetterBuildersWands-1.10.2-0.11.0.215+2d66774.jar
BiblioCraft[v2.2.1][MC1.10.2].jar
BigDoors-1.10.2-1.3.0.jar
BloodArsenal-1.10.2-2.0.1-17.jar
BloodMagic-1.10.2-2.1.5-74.jar
Bloodmoon-MC1.10.2-1.5.1.jar
Bookshelf-1.10.2-1.4.4.344.jar
Botania r1.9-340.jar
Cavern_1.10.2-v1.5.5.jar
Chameleon-1.10-2.2.2.jar
chameleoncreepers-1.4.1-1.10.2.jar
Chisel-MC1.10.2-0.0.8.12.jar
coroutil-1.10.2-1.1.13.jar
CraftTweaker-1.10.2-3.0.20.jar
CyclopsCore-1.9.4-0.9.2.jar
Decocraft-2.3.6.1_1.10.2.jar
DoomlikeDungeons-1.9.0-MC1.10.jar
druidry(2016.9.26)(1.9.4).jar
embers-0.104.jar
EnchantingPlus-1.10.2-4.1.0.116.jar
EvilCraft-1.10.2-0.10.20.jar
ExtraFood-1.10.2-0.8.6.jar
FastLeafDecay-v11.jar
Forgelin-1.4.0.jar
GrimoireOfGaia3-1.10.2-1.5.3.jar
Guide-API-1.10.2-2.0.3-46.jar
hardcoreWither-1.10.2-2.2.3-beta-4bd2a01-universal.jar
InfernalMobs-1.10.jar
InventoryTweaks-1.62-dev-66.jar
IronBackpacks-1.10.2-2.2.23.jar
jei_1.10.2-3.14.7.415.jar
journeymap-1.10.2-5.4.6.jar
JustEnoughButtons
justenoughbuttons-1.10.2-1.7.1.jar
justenoughdimensions-1.10.2-1.3.5.jar
LevelUp!-0.12.8-1.10.2.jar
librarianlib-1.10.1.jar
LycanitesMobsComplete 1.15.1.5 [1.10.2].jar
malisiscore-1.10.2-4.3.0.jar
malisisdoors-1.10.2-5.2.0.jar
Mantle-1.10.2-1.1.5.jar
mobtotems-1.10.2-0.1.2.jar
Morpheus-1.10.2-3.1.12.jar
mysticalagriculture[1.10.2]-1.4.3.jar
NaturalPledge-r1.10.jar
nethercore-1.10.2-2.0.3.jar
Overlord-1.10.2-2.1.1.jar
ProjectE-1.10.2-PE1.2.0.jar
PSIonicUpgrades-r1.15.jar
Psi-r1.0-42.jar
Quark-r1.1-70.jar
Reliquary-1.10.2-1.3.3.639.jar
RoguelikeDungeons-1.10.2-1.5.7.jar
roots-0.208.jar
RTG-1.10.2-4.1.2.4.jar
shetiphiancore-1.10.0-3.3.7.jar
SoulShards-TOW-1.10.2-2.6.7-48.jar
spongeforge-1.10.2-2221-5.2.0-BETA-2219.jar
StorageDrawers-1.10.2-3.6.1.jar
TamModized-1.10.2-0.6.2.jar
terraqueous-1.10.0-1.2.18.jar
Totemic-1.10.2-0.8.1.jar
vitality-2.4.jar
VoidCraft-1.10.2-0.16.1.jar
Waila-1.7.0-B3_1.9.4.jar
WearableBackpacks-1.10.2-1.6.0.jar
worldedit-forge-mc1.10.2-6.1.4-dist.jar
zombieawareness-1.10.2-1.11.6.jar
```

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/64467d2ed5e9f124c9cb50f5299c48c7a9fb8a30
