### ISSUE TITLE
 Could not pass SpawnEntityEvent

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#343]
This is probably a variant of #342 

While using
griefprevention-1.10.2-2.3.1.269.jar
spongeforge-1.10.2-2221-5.2.0-BETA-2219.jar
(and a bunch of mods),
the following error is reported:
```
[16:44:53] [Server thread/ERROR] [Sponge]: Could not pass SpawnEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException: 1
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getPermissionIdentifier(GPPermissionHandler.java:323) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getPermissionIdentifier(GPPermissionHandler.java:291) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getClaimPermission(GPPermissionHandler.java:81) ~[GPPermissionHandler.class:?]
>       at me.ryanhamshire.griefprevention.listener.EntityEventHandler$1.test(EntityEventHandler.java:226) ~[EntityEventHandler$1.class:?]
>       at me.ryanhamshire.griefprevention.listener.EntityEventHandler$1.test(EntityEventHandler.java:202) ~[EntityEventHandler$1.class:?]
>       at org.spongepowered.api.event.entity.AffectEntityEvent.filterEntities(AffectEntityEvent.java:120) ~[AffectEntityEvent.class:1.10.2-2221-5.2.0-BETA-2219]
>       at me.ryanhamshire.griefprevention.listener.EntityEventHandler.onEntitySpawn(EntityEventHandler.java:202) ~[EntityEventHandler.class:?]
>       at org.spongepowered.common.event.listener.SpawnEntityEventListener_EntityEventHandler_onEntitySpawn163.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:284) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.block.BlockDropItemsPhaseState.lambda$unwind$1(BlockDropItemsPhaseState.java:108) ~[BlockDropItemsPhaseState.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) [CapturedSupplier.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.block.BlockDropItemsPhaseState.unwind(BlockDropItemsPhaseState.java:93) [BlockDropItemsPhaseState.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.phase.block.BlockPhase.unwind(BlockPhase.java:73) [BlockPhase.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:251) [CauseTracker.class:1.10.2-2221-5.2.0-BETA-2219]
>       at net.minecraft.block.Block.handler$onDropBlockAsItemWithChanceReturn$zzl000(Block.java:2749) [akf.class:?]
>       at net.minecraft.block.Block.func_180653_a(Block.java:555) [akf.class:?]
>       at net.minecraft.block.BlockLeaves.func_180653_a(BlockLeaves.java:210) [amy.class:?]
>       at net.minecraft.block.Block.func_176226_b(Block.java:537) [akf.class:?]
>       at net.minecraft.block.BlockLeaves.func_176235_d(BlockLeaves.java:636) [amy.class:?]
>       at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:173) [amy.class:?]
>       at org.spongepowered.common.event.tracking.TrackingUtil.updateTickBlock(TrackingUtil.java:276) [TrackingUtil.class:1.10.2-2221-5.2.0-BETA-2219]
>       at net.minecraft.world.WorldServer.redirect$onUpdateTick$zjo000(WorldServer.java:2174) [ls.class:?]
>       at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744) [ls.class:?]
>       at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218) [ls.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by LemADEC** [comment]
A few mores from the logs
```
[19:43:23] [Server thread/ERROR] [Sponge]: Could not pass SpawnEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:24] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:24] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:24] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:25] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:25] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:25] [Server thread/ERROR] [Sponge]: Could not pass InteractEntityEvent$Primary$MainHand$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:25] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:26] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:26] [Server thread/ERROR] [Sponge]: Could not pass InteractEntityEvent$Primary$MainHand$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:26] [Server thread/ERROR] [Sponge]: Could not pass InteractEntityEvent$Primary$MainHand$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:37] [Server thread/ERROR] [Sponge]: Could not pass SpawnEntityEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
[19:43:39] [Server thread/ERROR] [Sponge]: Could not pass InteractEntityEvent$Primary$MainHand$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/magmayhem/./plugins/griefprevention-1.10.2-2.3.1.269.jar}
java.lang.ArrayIndexOutOfBoundsException
```
