### ISSUE TITLE
ChangeBlockEvent exception

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#345]
As of spongeforge-1.10.2-2254-5.2.0-BETA-2230.jar + griefprevention-1.10.2-2.3.1.271.jar, the following exceptions were observed while testing a new light modpack:
```
[19:13:37] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to pr
event all forms of grief., source=/home/magewars/./plugins/griefprevention-1.10.2-2.3.1.271.jar}
net.minecraft.util.ReportedException: Exception generating new chunk
>       at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:149) ~[lr.class:?]
>       at net.minecraft.world.World.func_72964_e(World.java:303) ~[aid.class:?]
>       at net.minecraft.world.World.func_175726_f(World.java:298) ~[aid.class:?]
>       at net.minecraft.world.World.func_180495_p(World.java:5688) ~[aid.class:?]
>       at net.minecraft.world.WorldServer.createSnapshot(WorldServer.java:2462) ~[ls.class:?]
>       at org.spongepowered.api.world.extent.Extent.createSnapshot(Extent.java:200) ~[Extent.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.api.world.Location.createSnapshot(Location.java:640) ~[Location.class:1.10.2-2254-5.2.0-BETA-2230]
>       at me.ryanhamshire.griefprevention.visual.Visualization.addTopLine(Visualization.java:366) ~[Visualization.class:?]
>       at me.ryanhamshire.griefprevention.visual.Visualization.addVisuals2D(Visualization.java:319) ~[Visualization.class:?]
>       at me.ryanhamshire.griefprevention.visual.Visualization.addClaimElements(Visualization.java:279) ~[Visualization.class:?]
>       at me.ryanhamshire.griefprevention.visual.Visualization.createClaimBlockVisuals(Visualization.java:224) ~[Visualization.class:?]
>       at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPlace(BlockEventHandler.java:776) ~[BlockEventHandler.class:?]
>       at org.spongepowered.common.event.listener.PlaceListener_BlockEventHandler_onBlockPlace123.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:284) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:640) ~[TrackingUtil.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:547) ~[TrackingUtil.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$null$40(PacketFunction.java:836) ~[PacketFunction.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) ~[CapturedSupplier.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$43(PacketFunction.java:834) ~[PacketFunction.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322) [PacketPhase.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:220) [CauseTracker.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:157) [PacketUtil.class:1.10.2-2254-5.2.0-BETA-2230]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjf000(SourceFile:539) [fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeImplHooks.class:1.10.2-2254-5.2.0-BETA-2230]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Chunk coordinates are not valid-1875000, 1875000
>       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.10.2.jar:?]
>       at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:64) ~[ChunkPrimerBuffer.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:58) ~[ChunkPrimerBuffer.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:242) ~[SpongeChunkGenerator.class:1.10.2-2254-5.2.0-BETA-2230]
>       at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140) ~[lr.class:?]
>       ... 39 more
[19:13:40] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to pr
event all forms of grief., source=/home/magewars/./plugins/griefprevention-1.10.2-2.3.1.271.jar}
net.minecraft.util.ReportedException: Exception generating new chunk
>       at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:149) ~[lr.class:?]
>       at net.minecraft.world.World.func_72964_e(World.java:303) ~[aid.class:?]
>       at net.minecraft.world.World.func_175726_f(World.java:298) ~[aid.class:?]
>       at net.minecraft.world.World.func_180495_p(World.java:5688) ~[aid.class:?]
>       at net.minecraft.world.WorldServer.createSnapshot(WorldServer.java:2462) ~[ls.class:?]
>       at org.spongepowered.api.world.extent.Extent.createSnapshot(Extent.java:200) ~[Extent.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.api.world.Location.createSnapshot(Location.java:640) ~[Location.class:1.10.2-2254-5.2.0-BETA-2230]
>       at me.ryanhamshire.griefprevention.visual.Visualization.addTopLine(Visualization.java:366) ~[Visualization.class:?]
>       at me.ryanhamshire.griefprevention.visual.Visualization.addVisuals2D(Visualization.java:319) ~[Visualization.class:?]
>       at me.ryanhamshire.griefprevention.visual.Visualization.addClaimElements(Visualization.java:279) ~[Visualization.class:?]
>       at me.ryanhamshire.griefprevention.visual.Visualization.createClaimBlockVisuals(Visualization.java:224) ~[Visualization.class:?]
>       at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPlace(BlockEventHandler.java:776) ~[BlockEventHandler.class:?]
>       at org.spongepowered.common.event.listener.PlaceListener_BlockEventHandler_onBlockPlace123.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:284) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:640) ~[TrackingUtil.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:547) ~[TrackingUtil.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$null$40(PacketFunction.java:836) ~[PacketFunction.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) ~[CapturedSupplier.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$43(PacketFunction.java:834) ~[PacketFunction.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322) [PacketPhase.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:220) [CauseTracker.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:157) [PacketUtil.class:1.10.2-2254-5.2.0-BETA-2230]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjf000(SourceFile:539) [fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeImplHooks.class:1.10.2-2254-5.2.0-BETA-2230]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Chunk coordinates are not valid-1875000, 1875000
>       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.10.2.jar:?]
>       at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:64) ~[ChunkPrimerBuffer.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:58) ~[ChunkPrimerBuffer.class:1.10.2-2254-5.2.0-BETA-2230]
>       at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:242) ~[SpongeChunkGenerator.class:1.10.2-2254-5.2.0-BETA-2230]
>       at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140) ~[lr.class:?]
>       ... 39 more
```

**Comment by LemADEC** [comment]
Looks like chunk coordinates are invalid, no idea what's causing it

**Comment by FiveEYZ** [comment]
just saw this error in my logs
error: https://gist.github.com/FiveEYZ/76393bb65de32e6eb7b9c2ed95347621
fml.log https://paste.ubuntu.com/24578700/

using:
GP build 295
SF build 2326

**Comment by bloodmc** [comment]
Reopen if this occurs with latest builds.

**Comment by dabaer** [comment]
I'm still seeing this with 1.12.2-4.3.0.687. Corrupts the stack frame and crashes the server.

```
Could not pass ChangeBlockEvent$Pre$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.687, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefP
revention, source=/home/server/modpacks/cruxnew/./plugins/griefprevention-1.12.2-4.3.0.687.jar}
java.lang.NoSuchFieldError: BLOCK_EVENT_PROCESS
        at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPre(BlockEventHandler.java:129) ~[BlockEventHandler.class:1.12.2-4.3.0.687]
        at org.spongepowered.common.event.listener.PreListener_BlockEventHandler_onBlockPre152.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.2]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.2]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2768-7.1.2]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.2]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:458) [SpongeEventManager.class:1.12.2-2768-7.1.2]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) [SpongeImpl.class:1.12.2-2768-7.1.2]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:530) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.2]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:488) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.2]
        at net.minecraft.block.BlockLeaves.redirect$onSpongeBreakBlock$bba000(BlockLeaves.java:1078) [arr.class:?]
        at net.minecraft.block.BlockLeaves.func_180663_b(BlockLeaves.java:58) [arr.class:?]
        at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:2278) [axw.class:?]
        at org.spongepowered.common.event.tracking.PhaseTracker.setBlockState(PhaseTracker.java:791) [PhaseTracker.class:1.12.2-2768-7.1.2]
        at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2753) [oo.class:?]
        at net.minecraft.world.gen.feature.WorldGenerator.func_175903_a(WorldGenerator.java:37) [azu.class:?]
        at net.minecraft.world.gen.feature.WorldGenTrees.func_180709_b(WorldGenTrees.java:132) [bax.class:?]
        at net.minecraft.world.gen.feature.WorldGenTrees.placeObject(WorldGenTrees.java:625) [bax.class:?]
        at org.spongepowered.common.world.gen.populators.ForestPopulator.populate(ForestPopulator.java:89) [ForestPopulator.class:1.12.2-2768-7.1.2]
        at org.spongepowered.api.world.gen.Populator.populate(Populator.java:97) [Populator.class:1.12.2-2768-7.1.2]
        at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:247) [SpongeChunkGeneratorForge.class:1.12.2-2768-7.1.2]
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019) [axw.class:?]
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990) [axw.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) [on.class:?]
        at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bci000(PlayerChunkMapEntry.java:1079) [ot.class:?]
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) [ot.class:?]
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) [ou.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by LemADEC** [comment]
@dabaer open a new issue with full logs
