### ISSUE TITLE
NPE with /claimslist on offline player

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#356]
As of 
griefprevention-1.10.2-2.3.1.271.jar
spongeforge-1.10.2-2254-5.2.0-BETA-2231.jar
forge-1.10.2-12.18.3.2239-universal.jar
when an admin type /claimslist xxx where xxx is an offline player, the following NPE happens:
```
[15:29:46] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'claimslist Mario167' for source EntityPlayerMP['LemADEC'/22604, l='Azgard', x=-2330.50, y=68.00, z=-265.50]: null
java.lang.NullPointerException
>       at me.ryanhamshire.griefprevention.command.CommandClaimList.execute(CommandClaimList.java:99) ~[CommandClaimList.class:?]
>       at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2254-5.2.0-BETA-2231]
>       at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2254-5.2.0-BETA-2231]
>       at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:295) ~[SpongeCommandManager.class:1.10.2-2254-5.2.0-BETA-2231]
>       at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
>       at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
>       at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
>       at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:158) ~[PacketUtil.class:1.10.2-2254-5.2.0-BETA-2231]
>       at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:157) [CauseTracker.class:1.10.2-2254-5.2.0-BETA-2231]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:157) [PacketUtil.class:1.10.2-2254-5.2.0-BETA-2231]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjf000(SourceFile:539) [fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeImplHooks.class:1.10.2-2254-5.2.0-BETA-2231]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by LemADEC** [comment]
Issue is reproduced with
griefprevention-1.10.2-2.3.1.272.jar
spongeforge-1.10.2-2254-5.2.0-BETA-2245.jar
forge-1.10.2-12.18.3.2254-universal.jar
as seen below:
```
[16:01:08] [Server thread/INFO] [nucleus]: LemADEC ran the command: /claimslist Mario167
[16:01:08] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'claimslist Mario167' for source EntityPlayerMP['LemADEC'/548, l='Azgard', x=-2331.00, y=68.00, z=-266.00]: null
java.lang.NullPointerException
>       at me.ryanhamshire.griefprevention.command.CommandClaimList.execute(CommandClaimList.java:99) ~[CommandClaimList.class:?]
>       at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2254-5.2.0-BETA-2245]
>       at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2254-5.2.0-BETA-2245]
>       at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:295) ~[SpongeCommandManager.class:1.10.2-2254-5.2.0-BETA-2245]
>       at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
>       at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
>       at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
>       at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:158) ~[PacketUtil.class:1.10.2-2254-5.2.0-BETA-2245]
>       at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:157) [CauseTracker.class:1.10.2-2254-5.2.0-BETA-2245]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:157) [PacketUtil.class:1.10.2-2254-5.2.0-BETA-2245]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjg000(SourceFile:539) [fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeImplHooks.class:1.10.2-2254-5.2.0-BETA-2245]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3931) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Issue is not reproduced once player is online.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/a112119921ad360cf56cf63905d67355a57d32e0
