### ISSUE TITLE
GriefPrevention not loading on SkyFactory 3 server

### ISSUE THREAD

**Issue by JaSpr** [MinecraftPortCentral/GriefPrevention#367]
Our new SkyFactory 3 server is not letting grief prevention load.  We're getting the following error during PreInitialization:

```
Could not pass FMLPreInitializationEvent to Plugin{id=griefprevention, name=GriefPrevention, version=2.3.1, description=This plugin is designed to prevent all forms of grief., source=/home/potatosaucevfx/Desktop/SF3Server/mods/griefprevention-1.10.2-2.3.1.272.jar}
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_121]
        at me.ryanhamshire.griefprevention.GriefPreventionPlugin.onPreInit(GriefPreventionPlugin.java:403) ~[GriefPreventionPlugin.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_GriefPreventionPlugin_onPreInit5.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2254-5.2.0-BETA-2264]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2264]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) [SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2264]
```

Full stack trace:

https://gist.github.com/JaSpr/40aae54fe783d4f1747df2e44b8e71e4

**Comment by PotatoSauceVFX** [comment]
@JaSpr and I are using:
- spongeforge-1.10.2-2254-5.2.0-BETA-2264
- griefprevention-1.10.2-2.3.1.272
- SkyClaims-0.19.1-beta 
- forge-1.10.2-12.18.3.2254-universal

We did check and it still gets the same error when we use sponge 2259 and try starting the server without sky claims. This doesn't crash the server it just doesn't load griefPrevention.

**Comment by PotatoSauceVFX** [comment]
griefprevention-1.10.2-2.3.1.278 gives the same error.

**Comment by bloodmc** [comment]
GP requires a permissions plugin. Install LuckPerms and you will have no issue.

**Comment by JaSpr** [comment]
Thanks! We had forgotten to copy over the PermissionManager jar!
