### ISSUE TITLE
Could Not Load Config

### ISSUE THREAD

**Issue by SjsolisZXA** [MinecraftPortCentral/GriefPrevention#384]
**Grief Prevention Version:** griefprevention-1.11.2-3.1.1.289
**Sponge Forge:** spongeforge-1.11.2-2282-7.0.0-BETA-2302

`[02:58:11] [Server thread/ERROR] [Sponge]: Could not pass FMLServerAboutToStartEvent to Plugin{id=griefprevention, name=GriefPrevention, version=3.1.1, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=C:\Users\Salva\Desktop\Sponge Servers\Official Sponge 1.11.2\mods\griefprevention-1.11.2-3.1.1.289.jar}
java.lang.ExceptionInInitializerError
        at me.ryanhamshire.griefprevention.GriefPreventionPlugin.loadConfig(GriefPreventionPlugin.java:1460) ~[GriefPreventionPlugin.class:?]
        at me.ryanhamshire.griefprevention.GriefPreventionPlugin.onServerAboutToStart(GriefPreventionPlugin.java:720) ~[GriefPreventionPlugin.class:?]
        at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_GriefPreventionPlugin_onServerAboutToStart20.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2282-7.0.0-BETA-2302]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2302]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2302]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:212) [SpongeMod.class:1.11.2-2282-7.0.0-BETA-2302]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:553) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:949) [Loader.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:265) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at me.ryanhamshire.griefprevention.DataStore.<clinit>(DataStore.java:129) ~[DataStore.class:?]
        ... 34 more`

**Comment by bloodmc** [comment]
GP requires a permission plugin.
