### ISSUE TITLE
NPE when a player try to create a claim

### ISSUE THREAD

**Issue by joserobjr** [MinecraftPortCentral/GriefPrevention#437]
For some reason, he can't create a claim, no error message is sent to him but this NPE is logged.

Seems to affect only him on the server.

```java
[18:35:45] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=4.1.0, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=/home/mc-test/1.11.2/mods/griefprevention-1.11.2-4.1.0.343.jar}
java.lang.NullPointerException
        at me.ryanhamshire.griefprevention.permission.GPOptionHandler.checkClaimOption(GPOptionHandler.java:96) ~[GPOptionHandler.class:1.11.2-4.1.0.343]
        at me.ryanhamshire.griefprevention.permission.GPOptionHandler.getClaimOptionDouble(GPOptionHandler.java:40) ~[GPOptionHandler.class:1.11.2-4.1.0.343]
        at me.ryanhamshire.griefprevention.claim.GPClaim$ClaimBuilder.build(GPClaim.java:2578) ~[GPClaim$ClaimBuilder.class:1.11.2-4.1.0.343]
        at me.ryanhamshire.griefprevention.DataStore.createClaim(DataStore.java:400) ~[DataStore.class:1.11.2-4.1.0.343]
        at me.ryanhamshire.griefprevention.DataStore.createClaim(DataStore.java:389) ~[DataStore.class:1.11.2-4.1.0.343]
        at me.ryanhamshire.griefprevention.listener.PlayerEventHandler.onPlayerHandleShovelAction(PlayerEventHandler.java:2450) ~[PlayerEventHandler.class:1.11.2-4.1.0.343]
        at me.ryanhamshire.griefprevention.listener.PlayerEventHandler.onPlayerInteractBlockSecondary(PlayerEventHandler.java:1746) ~[PlayerEventHandler.class:1.11.2-4.1.0.343]
        at org.spongepowered.common.event.listener.SecondaryListener_PlayerEventHandler_onPlayerInteractBlockSecondary183.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2393-6.1.0-BETA-2542]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.11.2-2393-6.1.0-BETA-2542]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:283) ~[SpongeModEventManager.class:1.11.2-2393-6.1.0-BETA-2542]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) ~[SpongeModEventManager.class:1.11.2-2393-6.1.0-BETA-2542]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) ~[SpongeModEventManager.class:1.11.2-2393-6.1.0-BETA-2542]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) ~[SpongeImpl.class:1.11.2-2393-6.1.0-BETA-2542]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:543) ~[SpongeCommonEventFactory.class:1.11.2-2393-6.1.0-BETA-2542]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:533) ~[SpongeCommonEventFactory.class:1.11.2-2393-6.1.0-BETA-2542]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1184) ~[lz.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zha000(NetHandlerPlayServer.java:2298) ~[mi.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:685) ~[mi.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jm.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jm.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:145) ~[PacketUtil.class:1.11.2-2393-6.1.0-BETA-2542]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.11.2-2393-6.1.0-BETA-2542]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:144) [PacketUtil.class:1.11.2-2393-6.1.0-BETA-2542]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjm000(SourceFile:539) [fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:256) [SpongeImplHooks.class:1.11.2-2393-6.1.0-BETA-2542]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhl000(MinecraftServer.java:3953) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
```

**Comment by joserobjr** [comment]
This actually happened with me too when I removed myself from the admin group.

**Comment by joserobjr** [comment]
It's related with the `griefprevention.admin.claim.override.limit` permission.
