### ISSUE TITLE
/trust does not work properly? 

### ISSUE THREAD

**Issue by codydbgt** [MinecraftPortCentral/GriefPrevention#463]
/trust rftools_builder does not work nor do offline players

https://i.gyazo.com/5379eecfc933bc0b0d85cc3f3e4f8bd1.png

**Comment by bloodmc** [comment]
Paste the output of /gpversion and upload your fml-server-latest.log

**Comment by codydbgt** [comment]
[18:21:57] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'trust openmodularturrets:fakeplayer' for source EntityPlayerMP['codydbgt'/4140, l='world', x=120.95, y=74.12, z=-276.90]: Invalid username openmodularturrets:fakeplayer
java.lang.IllegalArgumentException: Invalid username openmodularturrets:fakeplayer
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[minecraft_server.1.11.2.jar:?]
        at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:59) ~[SpongeUserStorageService.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.getValue(GenericArguments.java:1132) ~[GenericArguments$UserCommandElement.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.api.command.args.PatternMatchingCommandElement.parseValue(PatternMatchingCommandElement.java:59) ~[PatternMatchingCommandElement.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.api.command.args.GenericArguments$UserCommandElement.parseValue(GenericArguments.java:1111) ~[GenericArguments$UserCommandElement.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.api.command.args.CommandElement.parse(CommandElement.java:83) ~[CommandElement.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.api.command.args.GenericArguments$FirstParsingCommandElement.parse(GenericArguments.java:478) ~[GenericArguments$FirstParsingCommandElement.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.api.command.spec.CommandSpec.populateContext(CommandSpec.java:311) ~[CommandSpec.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:358) ~[CommandSpec.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:296) ~[SpongeCommandManager.class:1.11.2-2393-6.1.0-BETA-2549]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) ~[mi.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) ~[mi.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[ip.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[ip.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:145) ~[PacketUtil.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.11.2-2393-6.1.0-BETA-2549]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:144) [PacketUtil.class:1.11.2-2393-6.1.0-BETA-2549]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjm000(SourceFile:539) [fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:256) [SpongeImplHooks.class:1.11.2-2393-6.1.0-BETA-2549]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhl000(MinecraftServer.java:3953) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by bloodmc** [comment]
Fixed in latest SF via commit

https://github.com/SpongePowered/SpongeAPI/commit/6059354741a815cd2a86b63274ba97f8530de84c
