### ISSUE TITLE
Error on SpongeForge 1.12.2 /trust groupname

### ISSUE THREAD

**Issue by Mr-Krab** [MinecraftPortCentral/GriefPrevention#480]
[09:02:40] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'trust elite' for source EntityPlayerMP['uppr'/0, l='world', x=-96.30, y=63.00, z=-5.70]: null
java.lang.NullPointerException: null
	at me.ryanhamshire.griefprevention.command.CommandHelper.handleGroupTrustCommand(CommandHelper.java:1102) ~[CommandHelper.class:1.12.1-4.3.0.442]
	at me.ryanhamshire.griefprevention.command.CommandTrust.execute(CommandTrust.java:54) ~[CommandTrust.class:1.12.1-4.3.0.442]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360) ~[CommandSpec.class:1.12.2-2486-7.0.0-BETA-2668]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-2486-7.0.0-BETA-2668]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-2486-7.0.0-BETA-2668]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2486-7.0.0-BETA-2668]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkd000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:271) [SpongeImplHooks.class:1.12.2-2486-7.0.0-BETA-2668]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zif000(MinecraftServer.java:4003) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by bloodmc** [comment]
dupe #514
