### ISSUE TITLE
No such element exception with twilight forest during boss battle

### ISSUE THREAD

**Issue by hunter688** [MinecraftPortCentral/GriefPrevention#495]
When fight with Lich King inside Twilight Forest, get console exceptions:

SF: 1.12.2-2503-7.0.0-BETA-2709
GP: 4.3.0.480 

<pre>
[19:39:56] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Teleport$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=4.3.0, description=This plugin is designed to prevent all forms of grief., url=https://git
hub.com/MinecraftPortCentral/GriefPrevention, source=/home/bukkit/mc-eden-1.12/mods/griefprevention-1.12.1-4.3.0.480.jar}
java.util.NoSuchElementException: Could not retrieve value for key 'sponge:teleport_type'
        at org.spongepowered.api.event.cause.EventContext.require(EventContext.java:114) ~[EventContext.class:1.12.2-2503-7.0.0-BETA-2709]
        at me.ryanhamshire.griefprevention.listener.EntityEventHandler.onEntityTeleport(EntityEventHandler.java:765) ~[EntityEventHandler.class:1.12.1-4.3.0.480]
        at org.spongepowered.common.event.listener.TeleportListener_EntityEventHandler_onEntityTeleport167.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2503-7.0.0-BETA-2709]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:316) [SpongeModEventManager.class:1.12.2-2503-7.0.0-BETA-2709]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:282) [SpongeModEventManager.class:1.12.2-2503-7.0.0-BETA-2709]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) [SpongeModEventManager.class:1.12.2-2503-7.0.0-BETA-2709]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333) [SpongeModEventManager.class:1.12.2-2503-7.0.0-BETA-2709]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:198) [SpongeImpl.class:1.12.2-2503-7.0.0-BETA-2709]
        at org.spongepowered.common.entity.EntityUtil.handleDisplaceEntityTeleportEvent(EntityUtil.java:319) [EntityUtil.class:1.12.2-2503-7.0.0-BETA-2709]
        at net.minecraft.entity.EntityLivingBase.func_184595_k(EntityLivingBase.java:3721) [vp.class:?]
        at twilightforest.entity.boss.EntityTFLich.findVecInLOSOf(EntityTFLich.java:413) [EntityTFLich.class:?]
        at twilightforest.entity.boss.EntityTFLich.teleportToSightOfEntity(EntityTFLich.java:380) [EntityTFLich.class:?]
        at twilightforest.entity.ai.EntityAITFLichShadows.func_75246_d(EntityAITFLichShadows.java:45) [EntityAITFLichShadows.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
        at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) [vq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346) [vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45) [ade.class:?]
        at twilightforest.entity.boss.EntityTFLich.func_70636_d(EntityTFLich.java:211) [EntityTFLich.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166) [vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [vq.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50) [ade.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:160) [TrackingUtil.class:1.12.2-2503-7.0.0-BETA-2709]
        at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkm000(WorldServer.java:2839) [oo.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1986) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831) [oo.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1948) [amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:6052) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2208) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

</pre>

**Comment by hunter688** [comment]
Temporary workaround is disabling GP for DIM7 (twilight forest)

**Comment by Rasgnarok** [comment]
Have you tested again with latest LP and GP?
