### ISSUE TITLE
Setting up any type of trust for groups causes a null pointer exception

### ISSUE THREAD

**Issue by FireflyHM** [MinecraftPortCentral/GriefPrevention#509]
Mods on the discord channel told me to open an issue, so here I am.

sponge vanilla 1.12.2-7.0.0-BETA-346, luckperms 3.4.54 and griefprevention 1.12.1-4.3.0.470

When I try to set up trust of any type to users, gp works as intended.
When I try to set up trust of any type to groups, gp throws a null pointer exception, similar to this:

java.lang.NullPointerException: null
        at me.ryanhamshire.griefprevention.command.CommandHelper.handleGroupTrustCommand(CommandHelper.java:1102) ~[CommandHelper.class:1.12.1-4.3.0.470]
        at me.ryanhamshire.griefprevention.command.CommandAccessTrust.execute(CommandAccessTrust.java:54) ~[CommandAccessTrust.class:1.12.1-4.3.0.470]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360) ~[CommandSpec.class:1.12.2-7.0.0-BETA-346]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-7.0.0-BETA-346]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-7.0.0-BETA-346]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:855) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:842) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-7.0.0-BETA-346]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjp000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:272) [SpongeImplHooks.class:1.12.2-7.0.0-BETA-346]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zib000(SourceFile:4175) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by bloodmc** [comment]
You are using an outdated build, update to latest.

http://files.minecraftforge.net/maven/me/ryanhamshire/griefprevention/index_1.12.1.html

**Comment by FireflyHM** [comment]
Updated to griefprevention-1.12.1-4.3.0.483, problem persists.

[11:15:11 ERROR] [Sponge]: Error occurred while executing command 'accesstrust blah' for source EntityPlayerMP['HerpDerp'/2765, l='world', x=2443.76, y=64.00, z=250.95]: null
java.lang.NullPointerException: null
        at me.ryanhamshire.griefprevention.command.CommandHelper.handleGroupTrustCommand(CommandHelper.java:1102) ~[CommandHelper.class:1.12.1-4.3.0.483]
        at me.ryanhamshire.griefprevention.command.CommandAccessTrust.execute(CommandAccessTrust.java:54) ~[CommandAccessTrust.class:1.12.1-4.3.0.483]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360) ~[CommandSpec.class:1.12.2-7.0.0-BETA-346]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-7.0.0-BETA-346]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-7.0.0-BETA-346]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:855) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:842) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-7.0.0-BETA-346]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjp000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:272) [SpongeImplHooks.class:1.12.2-7.0.0-BETA-346]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zib000(SourceFile:4175) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
