### ISSUE TITLE
Could not pass SaveWorldEvent$Post$Impl to Plugin{id=griefprevention

### ISSUE THREAD

**Issue by TomTheHero** [MinecraftPortCentral/GriefPrevention#582]
This keeps on spamming my console and although idk what it exactly causes i won't use griefprevention until has been fixed https://pastebin.com/qPp6XpKz

**Comment by TomTheHero** [comment]
It turns out to happend whenever you disable claims

**Comment by bloodmc** [comment]
The config is deprecated and I haven't had time to remove it. Simply don't give your players to create a claim in the world. You can find permissions here

https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Permissions

**Comment by TomTheHero** [comment]
Well, there are 3 claims somewhere, so how do i remvoe them if idk where they are?

**Comment by DrZoddiak** [comment]
@TomTheHero Just remove them in the GP config folder

**Comment by JadenH** [comment]
Here is the stack frame for this error. I ran into this as well. Going to configure the server with the workaround above.
```
 Could not pass SaveWorldEvent$Post$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=4.3.0, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=/home/user/eodminecraft/mods/griefprevention-1.12.2-4.3.0.533 (1).jar}
java.lang.NullPointerException: null
        at me.ryanhamshire.griefprevention.claim.GPClaimManager.save(GPClaimManager.java:432) ~[GPClaimManager.class:1.12.2-4.3.0.533]
        at me.ryanhamshire.griefprevention.listener.WorldEventHandler.onWorldSave(WorldEventHandler.java:100) ~[WorldEventHandler.class:1.12.2-4.3.0.533]
        at org.spongepowered.common.event.listener.PostListener_WorldEventHandler_onWorldSave187.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2586-7.1.0-BETA-2887]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.12.2-2586-7.1.0-BETA-2887]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:315) [SpongeModEventManager.class:1.12.2-2586-7.1.0-BETA-2887]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:367) [SpongeModEventManager.class:1.12.2-2586-7.1.0-BETA-2887]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2586-7.1.0-BETA-2887]
        at net.minecraft.world.WorldServer.handler$onSaveAllChunks$zlj000(WorldServer.java:2387) [oo.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1009) [oo.class:?]
        at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:532) [WorldManager.class:1.12.2-2586-7.1.0-BETA-2887]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:3947) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$zje000(MinecraftServer.java:3900) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:685) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```
