### ISSUE TITLE
Server timeout with water flow

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#638]
As of griefprevention-1.12.2-4.3.0.569.jar
+LuckPerms-Sponge-4.1.31build582.jar
+spongeforge-1.12.2-2611-7.1.0-BETA-3017.jar, server is timing out every 6 minutes while water is flowing in a RFTools builder mining area chunkloaded in the deep dark.

In the 120 crashes observed, 118 were java.lang.Error exception (i.e. server timeout).
Of those 118, 62 involved different lines in "me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getFlagOverride"
After that, there's references to org.spongepowered.common.entity.player.SpongeUser.getPermissionValue
org.spongepowered.common.entity.player.SpongeUser.hasPermission
org.spongepowered.common.entity.player.SpongeUser.getActiveContexts

Here's one of those callstacks:
```
java.lang.Error
	at java.lang.String.intern(Native Method)
	at me.lucko.luckperms.common.calculators.PermissionCalculator.getPermissionValue(PermissionCalculator.java:86)
	at me.lucko.luckperms.common.caching.type.PermissionCache.getPermissionValue(PermissionCache.java:119)
	at me.lucko.luckperms.sponge.service.internal.HolderSubject.getPermissionValue(HolderSubject.java:108)
	at me.lucko.luckperms.sponge.service.proxy.api7.SubjectProxy.lambda$getPermissionValue$2(SubjectProxy.java:110)
	at me.lucko.luckperms.sponge.service.proxy.api7.SubjectProxy$$Lambda$3138/1554445493.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at me.lucko.luckperms.sponge.service.proxy.api7.SubjectProxy.getPermissionValue(SubjectProxy.java:110)
	at org.spongepowered.common.entity.player.SpongeUser.getPermissionValue(SpongeUser.java:1164)
	at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getFlagOverride(GPPermissionHandler.java:348)
	at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getClaimPermission(GPPermissionHandler.java:156)
	at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getClaimPermission(GPPermissionHandler.java:91)
	at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPre(BlockEventHandler.java:175)
	at org.spongepowered.common.event.listener.PreListener_BlockEventHandler_onBlockPre170.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368)
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:431)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:371)
	at net.minecraft.block.BlockDynamicLiquid.handler$onCanFlowInto$zbp000(BlockDynamicLiquid.java:556)
	at net.minecraft.block.BlockDynamicLiquid.func_176373_h(BlockDynamicLiquid.java)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:117)
	at org.spongepowered.common.event.tracking.TrackingUtil.updateTickBlock(TrackingUtil.java:286)
	at net.minecraft.world.WorldServer.redirect$onUpdateTick$zlm000(WorldServer.java:2242)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:736)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

This might be related to https://github.com/MinecraftPortCentral/GriefPrevention/issues/396
however in this case, there's no defined claim (apart from wilderness that is).

**Comment by LemADEC** [comment]
this might be due to Sponge issue itself, as reported here: https://github.com/SpongePowered/SpongeCommon/issues/1871

**Comment by bloodmc** [comment]
Related to https://github.com/SpongePowered/SpongeCommon/issues/2201
