### ISSUE TITLE
Blacklist NPE

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftPortCentral/GriefPrevention#673]
griefprevention-1.12.2-4.3.0.594
spongeforge-1.12.2-2705-7.1.0-BETA-3136
```
[16:19:15] [Server thread/ERROR]: [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=4.3.0, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=plugins/griefprevention-1.12.2-4.3.0.594.jar}
java.lang.NullPointerException: null
	at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getPermissionIdentifier(GPPermissionHandler.java:609) ~[GPPermissionHandler.class:1.12.2-4.3.0.594]
	at me.ryanhamshire.griefprevention.permission.GPPermissionHandler.getPermissionIdentifier(GPPermissionHandler.java:530) ~[GPPermissionHandler.class:1.12.2-4.3.0.594]
	at me.ryanhamshire.griefprevention.GriefPreventionPlugin.isSourceIdBlacklisted(GriefPreventionPlugin.java:2125) ~[GriefPreventionPlugin.class:1.12.2-4.3.0.594]
	at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPlace(BlockEventHandler.java:645) ~[BlockEventHandler.class:1.12.2-4.3.0.594]
	at org.spongepowered.common.event.listener.PlaceListener_BlockEventHandler_onBlockPlace193.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:340) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:415) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) ~[SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217) ~[SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:605) ~[TrackingUtil.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:524) ~[TrackingUtil.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.tracking.phase.tick.TileEntityTickPhaseState.lambda$unwind$0(TileEntityTickPhaseState.java:95) ~[TileEntityTickPhaseState.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.tracking.context.CapturedSupplier.acceptAndClearIfNotEmpty(CapturedSupplier.java:69) [CapturedSupplier.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.tracking.phase.tick.TileEntityTickPhaseState.unwind(TileEntityTickPhaseState.java:94) [TileEntityTickPhaseState.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.tracking.phase.tick.TileEntityTickPhaseState.unwind(TileEntityTickPhaseState.java:49) [TileEntityTickPhaseState.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:213) [PhaseTracker.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:439) [PhaseContext.class:1.12.2-2705-7.1.0-BETA-3136]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:246) [TrackingUtil.class:1.12.2-2705-7.1.0-BETA-3136]
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2871) [oo.class:?]
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zll000(WorldServer.java:2858) [oo.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6627) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2226) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by bloodmc** [comment]
Update to latest and provide a new stacktrace if it persists.
