### ISSUE TITLE
Could not pass InteractBlockEvent$Secondary$MainHand$Impl

### ISSUE THREAD

**Issue by iamtpage** [MinecraftPortCentral/GriefPrevention#741]
Steps to reproduce:
1. right click in claim with stick/shovel
2. no message pops up in chat about respective action
3. stacktrace in console

```
[GP] Running GriefPrevention 1.12.2-4.3.0.646
[GP] Running SpongeForge 1.12.2-2705-7.1.0-BETA-3355
[GP] Running luckperms 4.2.54
```

```
> [04:06:06] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=4.3.0, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=/home/container/./mods/plugins/griefprevention-1.12.2-4.3.0.646.jar}
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_151]
at me.ryanhamshire.griefprevention.GPPlayerData.revertActiveVisual(GPPlayerData.java:348) ~[GPPlayerData.class:1.12.2-4.3.0.646]
at me.ryanhamshire.griefprevention.listener.PlayerEventHandler.onPlayerHandleShovelAction(PlayerEventHandler.java:2403) ~[PlayerEventHandler.class:1.12.2-4.3.0.646]
at me.ryanhamshire.griefprevention.listener.PlayerEventHandler.onPlayerInteractBlockSecondary(PlayerEventHandler.java:1721) ~[PlayerEventHandler.class:1.12.2-4.3.0.646]
at org.spongepowered.common.event.listener.SecondaryListener_PlayerEventHandler_onPlayerInteractBlockSecondary175.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3355]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3355]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3355]
at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3355]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1689) [or.class:?]
at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zim000(NetHandlerPlayServer.java:2410) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3355]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zld000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3355]
at net.minecraft.server.MinecraftServer.redirect$onRun$zji000(MinecraftServer.java:3963) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

Note: right clicking with stick/shovel outside a claim and everything works fine, so does /claiminfo inside the claim

**Comment by bloodmc** [comment]
Unable to reproduce, most likely a corrupted claim or a bugged sponge build. Update to latest SF and create a new ticket if this can be reproduced on a fresh server.
