### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by VMBindraban** [MinecraftPortCentral/GriefPrevention#773]
I am getting this error while booting the server. Spigot 1.12.2.

```
21:49:13Could not load 'plugins/griefprevention-1.12.2-4.3.0.655.jar' in folder 'plugins'
Console 09/21/2018 21:49:13
21:49:13org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-8166d17]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.2.jar:git-Spigot-2cf50f0-8166d17]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-2cf50f0-8166d17]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-2cf50f0-8166d17]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-2cf50f0-8166d17]
at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
... 6 more
```

**Comment by Rasgnarok** [comment]
This the Sponge GriefPrevention github, not for Spigot. Sponge GP is a complete rewrite with no same codebase as Spigot. Ticket should be closed.

**Comment by bloodmc** [comment]
The spigot version can be found here
https://github.com/TechFortress/GriefPrevention
