### ISSUE TITLE
Got NullPointerException when applying claim tax task. 

### ISSUE THREAD

**Issue by jmecn** [MinecraftPortCentral/GriefPrevention#821]
Sponge Version: 7.1.0-SNAPSHOT
Forge Version: 1.12.2-1.12.2-14.23.5.2768
GriefPrevention: 1.12.2-4.3.0.639

**Description**

I set GriefPrevention `claim.bank-tax-system=true` and `claim.tax-apply-hour=12`. The server got a NPE when applying claim tax task.

https://github.com/MinecraftPortCentral/GriefPrevention/blob/d8862d33f53c99c369eb7aaedd19a07593b9b5c2/src/main/java/me/ryanhamshire/griefprevention/task/TaxApplyTask.java#L151

Maybe this is the line of code to blame.

https://github.com/MinecraftPortCentral/GriefPrevention/blob/6adfa5d867ed1b45d3196bd4520f5023dfcdb538/src/main/java/me/ryanhamshire/griefprevention/configuration/EconomyDataConfig.java#L95

**Console log**

````
[12:00:00] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task griefprevention-S-1 owned by Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.639, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=./mods/griefprevention-1.12.2-4.3.0.639.jar}, but an error occured.
java.lang.NullPointerException: null
    at me.ryanhamshire.griefprevention.configuration.EconomyDataConfig.setTaxPastDueDate(EconomyDataConfig.java:95) ~[EconomyDataConfig.class:1.12.2-4.3.0.639]
    at me.ryanhamshire.griefprevention.task.TaxApplyTask.handleClaimTax(TaxApplyTask.java:151) ~[TaxApplyTask.class:1.12.2-4.3.0.639]
    at me.ryanhamshire.griefprevention.task.TaxApplyTask.run(TaxApplyTask.java:107) ~[TaxApplyTask.class:1.12.2-4.3.0.639]
    at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2768-7.1.4]
    at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.4]
    at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2768-7.1.4]
    at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2768-7.1.4]
    at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2768-7.1.4]
    at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_171]
    at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2768-7.1.4]
    at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2768-7.1.4]
    at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2768-7.1.4]
    at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:351) [SpongeMod.class:1.12.2-2768-7.1.4]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_177_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) [EventBus.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
````

**Comment by bloodmc** [comment]
https://ore.spongepowered.org/blood/GriefPrevention/versions

Update to latest build which is 668.
