### ISSUE TITLE
Griefing with gravitational anomaly

### ISSUE THREAD

**Issue by runescapejon** [MinecraftPortCentral/GriefPrevention#849]
My versions are 
Griefprevention -1.12.2-4.3.0.681
Forge - 1.12.2-14.23.5.2815
SpongeForge - 1.12.2-2768-7.1.6-RC3616

Yet another way to grief but there is a config option to disable this but feel like you should know. So, if another mod use something like this it can be fixed already. Here how to perform this you would need 
MatterOverDrive mod currently i am using version `1.12.2-0.7.0.218` on their dev build latest one as of this moment. You get near of a claim that you do not have permission to and place down a gravitational anomaly and drop 64 Dilithium Crystal and it will start to suck up blocks around it by default it suck up about 4x4 radius.
demonstration gif: https://gyazo.com/3d993f79b9d27dc7dffccd820f1583e6

**Comment by bloodmc** [comment]
This mod is running its TE during Forge's WorldTickEvent and firing no events. It is impossible to determine a source when a mod does this.

```
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: java.lang.Exception: Stack trace
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPre(BlockEventHandler.java:116)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.common.event.listener.PreListener_BlockEventHandler_onBlockPre159.handle(Unknown Source)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:246)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:548)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:506)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.block.BlockLeaves.redirect$onSpongeBreakBlock$bbb000(BlockLeaves.java:1078)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.block.BlockLeaves.breakBlock(BlockLeaves.java:61)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:2391)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.common.event.tracking.TrackingUtil.captureBulkBlockChange(TrackingUtil.java:348)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.common.event.tracking.PhaseTracker.setBlockState(PhaseTracker.java:713)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.world.WorldServer.setBlockState(WorldServer.java:2861)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.world.World.setBlockToAir(World.java:468)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at matteroverdrive.tile.TileEntityGravitationalAnomaly.breakBlock(TileEntityGravitationalAnomaly.java:533)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at matteroverdrive.tile.TileEntityGravitationalAnomaly.manageBlockDestory(TileEntityGravitationalAnomaly.java:412)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at matteroverdrive.tile.TileEntityGravitationalAnomaly.onServerTick(TileEntityGravitationalAnomaly.java:142)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at matteroverdrive.handler.TickHandler.onWorldTick(TickHandler.java:104)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_142_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:851)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:415)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
[23:44:05] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.Thread.run(Thread.java:748)
```
The mod should be breaking blocks during TE tick, not doing it a hacky way via Forge's WorldTickEvent. Submit a ticket to the mod dev to fix it.
