### ISSUE TITLE
BLOCK_EVENT_PROCESS Missing

### ISSUE THREAD

**Issue by deadman96385** [MinecraftPortCentral/GriefPrevention#867]
Forge: 1.12.2-14.23.5.2768
Mods: Skyclaims, Greifprevention, LuckPerms, Nucleus, TotalEconomy
Plugin Version: 1.12.2-4.3.0.688 and 1.12.2-4.3.0.687

Setup a fresh forge server on centos and i get the following error which crashes the server once i join. Seems like the same issue as #866 

> [15:27:04] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Pre$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.687, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=./mods/griefprevention-1.12.2-4.3.0.687.jar}
java.lang.NoSuchFieldError: BLOCK_EVENT_PROCESS
at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPre(BlockEventHandler.java:129) ~[BlockEventHandler.class:1.12.2-4.3.0.687]
at org.spongepowered.common.event.listener.PreListener_BlockEventHandler_onBlockPre135.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.5]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:1.12.2-2768-7.1.5]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) [SpongeImpl.class:1.12.2-2768-7.1.5]
at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:545) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.5]
at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:503) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.5]
at net.minecraft.block.BlockDynamicLiquid.handler$onUpdateTickHead$zcb000(BlockDynamicLiquid.java:572) [aqe.class:?]
at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java) [aqe.class:?]
at net.minecraft.block.Block.func_180645_a(Block.java:508) [aow.class:?]
at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:303) [TrackingUtil.class:1.12.2-2768-7.1.5]
at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2158) [oo.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by bloodmc** [comment]
Using outdated SF build, update to SF 3616.
