### ISSUE TITLE
NPE with ActuallyAdditions block placer

### ISSUE THREAD

**Issue by LemADEC** [MinecraftPortCentral/GriefPrevention#870]
As of griefprevention-1.12.2-4.3.0.688 + spongeforge-1.12.2-2768-7.1.6-RC3616, an NPE is observed from ActuallyAdditions block placer.
This is observed on an FTB Continuum 1.6.0 public server.

```
18:18:48] [Server thread/ERROR] [Actually Additions]: Something that places Blocks at 1761, 56, 387 in World 0 threw an Exception! Don't let that happen again!
java.lang.NullPointerException: null
>       at net.minecraft.entity.player.EntityPlayerMP.func_71110_a(EntityPlayerMP.java:989) ~[oq.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.func_71120_a(EntityPlayerMP.java:984) ~[oq.class:?]
>       at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1293) ~[or.class:?]
>       at de.ellpeck.actuallyadditions.mod.util.WorldUtil.useItemAtSide(WorldUtil.java:193) [WorldUtil.class:?]
>       at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.doWork(TileEntityBreaker.java:100) [TileEntityBreaker.class:?]
>       at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.updateEntity(TileEntityBreaker.java:65) [TileEntityBreaker.class:?]
>       at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.func_73660_a(TileEntityBase.java:223) [TileEntityBase.class:?]
>       at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:229) [TrackingUtil.class:1.12.2-2768-7.1.6-RC3616]
>       at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2985) [oo.class:?]
>       at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zmd000(WorldServer.java:2972) [oo.class:?]
>       at net.minecraft.world.World.func_72939_s(World.java:6741) [amu.class:?]
>       at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2291) [oo.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

Coordinates are matching with a log block here:
![image](https://user-images.githubusercontent.com/4776032/54958206-47631100-4f55-11e9-8105-6b3e7e7b5003.png)
Note: the logs refers to TileEntityBreaker but it's a "Block placer" in-game, as seen below the log on the picture.

This is a fairly old base, so the issue was probably triggered by recent changes.

**Comment by LemADEC** [comment]
For reference, the issue appeared initially with a log similar to this:
```
[15:39:12] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.679, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=/home/direwolf20/./plugins/griefprevention-1.12.2-4.3.0.679.jar}
java.lang.NullPointerException: null
	at net.minecraft.entity.player.EntityPlayerMP.func_71053_j(EntityPlayerMP.java:1008) ~[oq.class:?]
	at me.ryanhamshire.griefprevention.listener.PlayerEventHandler.sendInteractBlockDenyMessage(PlayerEventHandler.java:2670) ~[PlayerEventHandler.class:1.12.2-4.3.0.679]
	at me.ryanhamshire.griefprevention.listener.PlayerEventHandler.onPlayerInteractBlockSecondary(PlayerEventHandler.java:1760) ~[PlayerEventHandler.class:1.12.2-4.3.0.679]
	at org.spongepowered.common.event.listener.SecondaryListener_PlayerEventHandler_onPlayerInteractBlockSecondary175.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.6-RC3616]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3616]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3616]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3616]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1229) [or.class:?]
	at de.ellpeck.actuallyadditions.mod.util.WorldUtil.useItemAtSide(WorldUtil.java:193) [WorldUtil.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.doWork(TileEntityBreaker.java:100) [TileEntityBreaker.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.updateEntity(TileEntityBreaker.java:65) [TileEntityBreaker.class:?]
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.func_73660_a(TileEntityBase.java:223) [TileEntityBase.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:229) [TrackingUtil.class:1.12.2-2768-7.1.6-RC3616]
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2985) [oo.class:?]
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zmd000(WorldServer.java:2972) [oo.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6241) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2291) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

After updating griefprevention, it changes to something like this:
```
[17:12:36] [Server thread/ERROR] [Actually Additions]: Something that places Blocks at 672, 78, 816 in World 0 threw an Exception! Don't let that happen again!
java.lang.NullPointerException: null
>       at net.minecraft.entity.player.EntityPlayerMP.func_71110_a(EntityPlayerMP.java:989) ~[oq.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.func_71120_a(EntityPlayerMP.java:984) ~[oq.class:?]
>       at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1293) ~[or.class:?]
>       at de.ellpeck.actuallyadditions.mod.util.WorldUtil.useItemAtSide(WorldUtil.java:193) [WorldUtil.class:?]
>       at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.doWork(TileEntityBreaker.java:100) [TileEntityBreaker.class:?]
>       at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.updateEntity(TileEntityBreaker.java:65) [TileEntityBreaker.class:?]
>       at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.func_73660_a(TileEntityBase.java:223) [TileEntityBase.class:?]
>       at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:229) [TrackingUtil.class:1.12.2-2768-7.1.6-RC3616]
>       at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2985) [oo.class:?]
>       at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zmd000(WorldServer.java:2972) [oo.class:?]
>       at net.minecraft.world.World.func_72939_s(World.java:6241) [amu.class:?]
>       at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2291) [oo.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```
