### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by lFreezingl** [MinecraftPortCentral/GriefPrevention#875]
Anyone have any idea what it might be causing and how to fix it?

```
[Server] Server thread/ERROR [Sponge]: Could not pass ChangeBlockEvent$Pre$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.688, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=./mods/griefprevention-1.12.2-4.3.0.688.jar}
31.03 11:01:36 [Server] INFO java.lang.NoSuchFieldError: BLOCK_EVENT_PROCESS
31.03 11:01:36 [Server] INFO at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPre(BlockEventHandler.java:129) ~[BlockEventHandler.class:1.12.2-4.3.0.688]
31.03 11:01:36 [Server] INFO at org.spongepowered.common.event.listener.PreListener_BlockEventHandler_onBlockPre377.handle(Unknown Source) ~[?:?]
31.03 11:01:36 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.5]
31.03 11:01:36 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
31.03 11:01:36 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.postEvent(SpongeModEventManager.java:361) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
31.03 11:01:36 [Server] INFO at org.spongepowered.mod.event.ForgeToSpongeEventFactory.createAndPostChangeBlockEventPre(ForgeToSpongeEventFactory.java:276) [ForgeToSpongeEventFactory.class:1.12.2-2768-7.1.5]
31.03 11:01:36 [Server] INFO at org.spongepowered.mod.event.ForgeToSpongeEventFactory.createAndPostSpongeEvent(ForgeToSpongeEventFactory.java:172) [ForgeToSpongeEventFactory.class:1.12.2-2768-7.1.5]
31.03 11:01:36 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:290) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
31.03 11:01:36 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:723) [EventBus.class:?]
31.03 11:01:36 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:697) [EventBus.class:?]
31.03 11:01:36 [Server] INFO at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:838) [ForgeHooks.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:283) [or.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:713) [or.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:693) [pa.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
31.03 11:01:36 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5]
31.03 11:01:36 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) [hv$1.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
31.03 11:01:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
31.03 11:01:36 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
31.03 11:01:36 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
31.03 11:01:36 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
31.03 11:01:36 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
31.03 11:01:36 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
```

**Comment by HeberonYT** [comment]
I have the same problem.
I have updated from version 4.3.0.662 to the new 4.3.0.688 and I am receiving this spam.
At the moment I have returned to the old version.

**Comment by bloodmc** [comment]
Stop using outdated SpongeForge builds. GP 688 requires 3616+

**Comment by Possemaster** [comment]
Sorry to update this post, but I have the same issue, latest Recommended SpongeForge (spongeforge-1.12.2-2768-7.1.5) with latest griefprevention (griefprevention-1.12.2-4.3.0.689)
It Consolespams with exact the same messages.
You tell us to use 3616+ but that is already SpongeForge 7.1.6 RC, and your plugin page tells us to use 7.1.5
