### ISSUE TITLE
Could not pass ChangeBlockEvent$Pre$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.689,

### ISSUE THREAD

**Issue by Potatoman233** [MinecraftPortCentral/GriefPrevention#890]
[04:09:58] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Pre$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.689, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=.\mods\[插件][领地]griefprevention-1.12.2-4.3.0.689.jar} 
java.lang.NoSuchFieldError: BLOCK_EVENT_PROCESS
at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPre(BlockEventHandler.java:129) ~[BlockEventHandler.class:1.12.2-4.3.0.689]
at org.spongepowered.common.event.listener.PreListener_BlockEventHandler_onBlockPre174.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.5]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:1.12.2-2768-7.1.5]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) [SpongeImpl.class:1.12.2-2768-7.1.5]
at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:545) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.5]
at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:503) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.5]
at net.minecraft.block.BlockLeaves.redirect$onSpongeBreakBlock$bap000(BlockLeaves.java:1078) [arr.class:?]
at net.minecraft.block.BlockLeaves.func_180663_b(BlockLeaves.java:58) [arr.class:?]
at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:2278) [axw.class:?]
at org.spongepowered.common.event.tracking.TrackingUtil.captureBulkBlockChange(TrackingUtil.java:355) [TrackingUtil.class:1.12.2-2768-7.1.5]
at org.spongepowered.common.event.tracking.PhaseTracker.setBlockState(PhaseTracker.java:712) [PhaseTracker.class:1.12.2-2768-7.1.5]
at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2749) [oo.class:?]
at net.minecraft.world.World.func_175698_g(World.java:398) [amu.class:?]
at net.minecraft.block.BlockLeaves.func_176235_d(BlockLeaves.java:632) [arr.class:?]
at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:173) [arr.class:?]
at net.minecraft.block.Block.func_180645_a(Block.java:508) [aow.class:?]
at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:303) [TrackingUtil.class:1.12.2-2768-7.1.5]
at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2158) [oo.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Potatoman233** [comment]
is there any newer version for sponge 7.

> [04:09:58] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Pre$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.689, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=.\mods[插件][领地]griefprevention-1.12.2-4.3.0.689.jar}
> java.lang.NoSuchFieldError: BLOCK_EVENT_PROCESS
> at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPre(BlockEventHandler.java:129) ~[BlockEventHandler.class:1.12.2-4.3.0.689]
> at org.spongepowered.common.event.listener.PreListener_BlockEventHandler_onBlockPre174.handle(Unknown Source) ~[?:?]
> at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.5]
> at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
> at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
> at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
> at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:1.12.2-2768-7.1.5]
> at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) [SpongeImpl.class:1.12.2-2768-7.1.5]
> at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:545) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.5]
> at org.spongepowered.common.event.SpongeCommonEventFactory.callChangeBlockEventPre(SpongeCommonEventFactory.java:503) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.5]
> at net.minecraft.block.BlockLeaves.redirect$onSpongeBreakBlock$bap000(BlockLeaves.java:1078) [arr.class:?]
> at net.minecraft.block.BlockLeaves.func_180663_b(BlockLeaves.java:58) [arr.class:?]
> at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:2278) [axw.class:?]
> at org.spongepowered.common.event.tracking.TrackingUtil.captureBulkBlockChange(TrackingUtil.java:355) [TrackingUtil.class:1.12.2-2768-7.1.5]
> at org.spongepowered.common.event.tracking.PhaseTracker.setBlockState(PhaseTracker.java:712) [PhaseTracker.class:1.12.2-2768-7.1.5]
> at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2749) [oo.class:?]
> at net.minecraft.world.World.func_175698_g(World.java:398) [amu.class:?]
> at net.minecraft.block.BlockLeaves.func_176235_d(BlockLeaves.java:632) [arr.class:?]
> at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:173) [arr.class:?]
> at net.minecraft.block.Block.func_180645_a(Block.java:508) [aow.class:?]
> at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:303) [TrackingUtil.class:1.12.2-2768-7.1.5]
> at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2158) [oo.class:?]
> at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) [oo.class:?]
> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
> at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
