### ISSUE TITLE
PlayerPotalEvent in 1.14

### ISSUE THREAD

**Issue by kakd** [MinecraftPortCentral/GriefPrevention#892]
Using Spigot 1.14, I get this error
`[18:04:00] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to GriefPrevention v16.11.6
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[server.jar:git-Spigot-1eece4f-5a37f43]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-1eece4f-5a37f43]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [server.jar:git-Spigot-1eece4f-5a37f43]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:757) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2015) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:369) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:232) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:341) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2211) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:147) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:396) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:140) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:234) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1077) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:953) [server.jar:git-Spigot-1eece4f-5a37f43]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:798) [server.jar:git-Spigot-1eece4f-5a37f43]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.useTravelAgent()Z
at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerPortal(PlayerEventHandler.java:1067) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-1eece4f-5a37f43]
... 19 more`

In order to reproduce, walk through a nether portal. It doesn't seem to be affecting anything other than just spamming the console, but I'm sure you added the event for a reason.

**Comment by kencinder** [comment]
This is GP for Sponge, not Spigot.

**Comment by kakd** [comment]
Whoops, thanks for letting me know
