### ISSUE TITLE
The Scheduler tried to run the task griefprevention Console Spam

### ISSUE THREAD

**Issue by Possemaster** [MinecraftPortCentral/GriefPrevention#894]
When placing a chest for the first time or using a golden shovel the console get spammed with below;
I also do not see the Gold and Glowstone, it does create the claim but resizing it is impossible as I cannot see what is happening.

MC Version: 1.12.2 (MODPACK Towncraft)
Forge Version: forge-1.12.2-14.23.5.2824-universal.jar
SpongeForge Version: spongeforge-1.12.2-2825-7.1.6-RC3693.jar
GriefPrevention Version: griefprevention-1.12.2-4.3.0.689.jar

```
[ERROR] [Sponge]: The Scheduler tried to run the task griefprevention-S-23 owned by Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.689, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=/home/gs-40986/./mods/plugins/griefprevention-1.12.2-4.3.0.689.jar}, but an error occured.

java.util.NoSuchElementException: No value present

at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_212]

at me.ryanhamshire.griefprevention.GPPlayerData.revertActiveVisual(GPPlayerData.java:361) ~[GPPlayerData.class:1.12.2-4.3.0.689]

at me.ryanhamshire.griefprevention.task.VisualizationApplicationTask.run(VisualizationApplicationTask.java:61) ~[VisualizationApplicationTask.class:1.12.2-4.3.0.689]

at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2825-7.1.6-RC3693]

at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2825-7.1.6-RC3693]

at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2825-7.1.6-RC3693]

at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2825-7.1.6-RC3693]

at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2825-7.1.6-RC3693]

at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_212]

at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2825-7.1.6-RC3693]

at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2825-7.1.6-RC3693]

at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2825-7.1.6-RC3693]

at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:418) [SpongeMod.class:1.12.2-2825-7.1.6-RC3693]

at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_509_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]

at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]

at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746) [EventBus.class:?]

at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696) [EventBus.class:?]

at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]

at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] 

```

The AbandonAllClaims and Trying to reclaim with the shovel also has the same issue and gets another console WARNING spam:
 
```
[WARNING] [Sponge]: /***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/

[WARNING] [Sponge]: /* Could not pass InteractBlockEvent$Secondary$MainHand$Impl */

[WARNING] [Sponge]: /***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/

[WARNING] [Sponge]: /* Could not pass the event InteractBlockEvent$Secondary$MainHand$Impl to an Event Listener! */

[WARNING] [Sponge]: /* */

[WARNING] [Sponge]: /* Since the event can be modified during the event's listener,

there could be adverse side effects of the exception occuring

such that duplications or other game breaking issues could exist.

Due to the nature of the exception, this is not likely an exception

that is covered by SpongeForge or Forge itself, and therefor should

be reported to the mod/plugin author first prior to reporting to

Sponge or Forge. */

[WARNING] [Sponge]: /* Owning Mod/Plugin: griefprevention */

[WARNING] [Sponge]: /* Exception: */

[WARNING] [Sponge]: /* java.util.NoSuchElementException: No value present */

[WARNING] [Sponge]: /* java.util.Optional.get(Optional.java:135) */

[WARNING] [Sponge]: /* me.ryanhamshire.griefprevention.GPPlayerData.revertActiveVisual(GPPlayerData.java:361) */

[WARNING] [Sponge]: /* me.ryanhamshire.griefprevention.listener.PlayerEventHandler.onPlayerHandleShovelAction(PlayerEventHandler.java:2457) */

[WARNING] [Sponge]: /* me.ryanhamshire.griefprevention.listener.PlayerEventHandler.handleItemInteract(PlayerEventHandler.java:1810) */

[WARNING] [Sponge]: /* me.ryanhamshire.griefprevention.listener.PlayerEventHandler.onPlayerInteractBlockSecondary(PlayerEventHandler.java:1654) */

[WARNING] [Sponge]: /* org.spongepowered.common.event.listener.SecondaryListener_PlayerEventHandler_onPlayerInteractBlockSecondary145.handle(Unknown Source) */

[WARNING] [Sponge]: /* org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) */

[WARNING] [Sponge]: /* org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385) */

[WARNING] [Sponge]: /* org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) */

[WARNING] [Sponge]: /* org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:450) */

[WARNING] [Sponge]: /* org.spongepowered.common.SpongeImplHooks.postForgeEventDataCompatForSponge(SpongeImplHooks.java:2027) */

[WARNING] [Sponge]: /* net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:845) */

[WARNING] [Sponge]: /* net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zjb000(NetHandlerPlayServer.java:2428) */

[WARNING] [Sponge]: /* net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) */

[WARNING] [Sponge]: /* net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) */

[WARNING] [Sponge]: /* net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) */

[WARNING] [Sponge]: /* org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) */

[WARNING] [Sponge]: /* net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlj000(SourceFile:539) */

[WARNING] [Sponge]: /* net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) */

[WARNING] [Sponge]: /* java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) */

[WARNING] [Sponge]: /* java.util.concurrent.FutureTask.run(FutureTask.java:266) */

[WARNING] [Sponge]: /* net.minecraft.util.Util.func_181617_a(SourceFile:529) */

[WARNING] [Sponge]: /* org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:305) */

[WARNING] [Sponge]: /* net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3965) */

[WARNING] [Sponge]: /* net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) */

[WARNING] [Sponge]: /* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) */

[WARNING] [Sponge]: /* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) */

[WARNING] [Sponge]: /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) */

[WARNING] [Sponge]: /* java.lang.Thread.run(Thread.java:748) */ 
```

**Comment by Possemaster** [comment]
Problem solved after using latest Forge Build
