### ISSUE TITLE
[1.10 branch] Config issue when setting claim name and/or farewell/greeting messages.

### ISSUE THREAD

**Issue by cartman-2000** [MinecraftPortCentral/GriefPrevention#94]
You get an exception in the logs when the config file loads for the claim when one of these things are set in the claim data file. And the Claim files that get the error won't load on server start anymore.

The server is running on windows 10 with Java1.8.0_91 64bit:
[22:23:48] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-05d0adc
    SpongeForge: 1.10.2-2002-5.0.0-BETA-1539
    Minecraft Forge: 12.18.0.2005

```
[21:33:41] [Server thread/INFO] [io.github.hsyyid.essentialcmds/]: [cartman2000] executed command claimname Spawn
[21:33:47] [Server thread/INFO] [io.github.hsyyid.essentialcmds/]: [cartman2000] executed command adminclaims 
[21:33:47] [HikariPool-1 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
[21:33:48] [HikariPool-2 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-2 - Pool stats (total=17, active=0, idle=17, waiting=0)
[21:33:48] [Server thread/INFO] [STDOUT/]: [me.ryanhamshire.griefprevention.event.PlayerEventHandler:onPlayerInteractBlockSecondary:1437]: PACKET RECEIVED
[21:33:50] [Server thread/INFO] [STDOUT/]: [me.ryanhamshire.griefprevention.event.PlayerEventHandler:onPlayerInteractBlockSecondary:1437]: PACKET RECEIVED
[21:33:51] [Server thread/INFO] [STDOUT/]: [me.ryanhamshire.griefprevention.event.PlayerEventHandler:onPlayerInteractBlockSecondary:1437]: PACKET RECEIVED
[21:33:51] [Server thread/ERROR] [Sponge/]: Failed to load configuration
org.spongepowered.api.data.persistence.InvalidDataException: Could not deserialize something correctly, likely due to bad type data.
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:88) ~[AbstractDataBuilder.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.common.data.SpongeDataManager.deserialize(SpongeDataManager.java:205) ~[SpongeDataManager.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.deserialize(TextConfigSerializer.java:71) ~[TextConfigSerializer.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.deserialize(TextConfigSerializer.java:56) ~[TextConfigSerializer.class:1.10.2-2002-5.0.0-BETA-1539]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:80) ~[spongeforge-1.10.2-2002-5.0.0-BETA-1539.jar:1.10.2-2002-5.0.0-BETA-1539]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:140) ~[spongeforge-1.10.2-2002-5.0.0-BETA-1539.jar:1.10.2-2002-5.0.0-BETA-1539]
	at me.ryanhamshire.griefprevention.configuration.ClaimStorageData.reload(ClaimStorageData.java:139) [ClaimStorageData.class:?]
	at me.ryanhamshire.griefprevention.configuration.ClaimStorageData.<init>(ClaimStorageData.java:95) [ClaimStorageData.class:?]
	at me.ryanhamshire.griefprevention.FlatFileDataStore.writeClaimToStorage(FlatFileDataStore.java:423) [FlatFileDataStore.class:?]
	at me.ryanhamshire.griefprevention.DataStore.addClaim(DataStore.java:359) [DataStore.class:?]
	at me.ryanhamshire.griefprevention.DataStore.createClaim(DataStore.java:557) [DataStore.class:?]
	at me.ryanhamshire.griefprevention.DataStore.resizeClaim(DataStore.java:881) [DataStore.class:?]
	at me.ryanhamshire.griefprevention.event.PlayerEventHandler.onPlayerHandleShovelAction(PlayerEventHandler.java:1859) [PlayerEventHandler.class:?]
	at me.ryanhamshire.griefprevention.event.PlayerEventHandler.onPlayerInteractBlockSecondary(PlayerEventHandler.java:1453) [PlayerEventHandler.class:?]
	at org.spongepowered.common.event.listener.MainHandListener_PlayerEventHandler_onPlayerInteractBlockSecondary63.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:221) [SpongeModEventManager.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:204) [SpongeModEventManager.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:249) [SpongeModEventManager.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:234) [SpongeModEventManager.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) [SpongeImpl.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:266) [SpongeCommonEventFactory.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:256) [SpongeCommonEventFactory.class:1.10.2-2002-5.0.0-BETA-1539]
	at net.minecraft.server.management.PlayerInteractionManager.handler$onProcessRightClick$0(PlayerInteractionManager.java:86) [lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java) [lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) [me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) [jk.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) [jk.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:119) [PacketUtil.class:1.10.2-2002-5.0.0-BETA-1539]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: org.spongepowered.api.data.persistence.InvalidDataException: org.spongepowered.api.text.serializer.TextParseException: Failed to parse JSON
	at org.spongepowered.api.text.serializer.TextConfigSerializer.buildContent(TextConfigSerializer.java:93) ~[TextConfigSerializer.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:86) ~[AbstractDataBuilder.class:1.10.2-2002-5.0.0-BETA-1539]
	... 38 more
Caused by: org.spongepowered.api.text.serializer.TextParseException: Failed to parse JSON
	at org.spongepowered.common.text.serializer.JsonTextSerializer.deserialize(JsonTextSerializer.java:50) ~[JsonTextSerializer.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.buildContent(TextConfigSerializer.java:91) ~[TextConfigSerializer.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:86) ~[AbstractDataBuilder.class:1.10.2-2002-5.0.0-BETA-1539]
	... 38 more
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2
	at com.google.gson.internal.Streams.parse(Streams.java:56) ~[Streams.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:501) ~[og.class:?]
	at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:512) ~[og.class:?]
	at net.minecraft.util.text.ITextComponent$Serializer.func_150699_a(ITextComponent.java:260) ~[ey$a.class:?]
	at org.spongepowered.common.text.serializer.JsonTextSerializer.deserialize(JsonTextSerializer.java:48) ~[JsonTextSerializer.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.buildContent(TextConfigSerializer.java:91) ~[TextConfigSerializer.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:86) ~[AbstractDataBuilder.class:1.10.2-2002-5.0.0-BETA-1539]
	... 38 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1336) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:538) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.internal.Streams.parse(Streams.java:42) ~[Streams.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:501) ~[og.class:?]
	at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:512) ~[og.class:?]
	at net.minecraft.util.text.ITextComponent$Serializer.func_150699_a(ITextComponent.java:260) ~[ey$a.class:?]
	at org.spongepowered.common.text.serializer.JsonTextSerializer.deserialize(JsonTextSerializer.java:48) ~[JsonTextSerializer.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.api.text.serializer.TextConfigSerializer.buildContent(TextConfigSerializer.java:91) ~[TextConfigSerializer.class:1.10.2-2002-5.0.0-BETA-1539]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:86) ~[AbstractDataBuilder.class:1.10.2-2002-5.0.0-BETA-1539]
	... 38 more
[21:33:51] [Server thread/INFO] [griefprevention/]: GriefPrevention: 05739abd-7bf3-4ced-873b-c57dfb72a68b java.lang.NullPointerException
	at me.ryanhamshire.griefprevention.claim.Claim.updateClaimStorageData(Claim.java:1035)
	at me.ryanhamshire.griefprevention.FlatFileDataStore.writeClaimToStorage(FlatFileDataStore.java:428)
	at me.ryanhamshire.griefprevention.DataStore.addClaim(DataStore.java:359)
	at me.ryanhamshire.griefprevention.DataStore.createClaim(DataStore.java:557)
	at me.ryanhamshire.griefprevention.DataStore.resizeClaim(DataStore.java:881)
	at me.ryanhamshire.griefprevention.event.PlayerEventHandler.onPlayerHandleShovelAction(PlayerEventHandler.java:1859)
	at me.ryanhamshire.griefprevention.event.PlayerEventHandler.onPlayerInteractBlockSecondary(PlayerEventHandler.java:1453)
	at org.spongepowered.common.event.listener.MainHandListener_PlayerEventHandler_onPlayerInteractBlockSecondary63.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:221)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:204)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:249)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:234)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:266)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:256)
	at net.minecraft.server.management.PlayerInteractionManager.handler$onProcessRightClick$0(PlayerInteractionManager.java:86)
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710)
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9)
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:119)
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

Contents of the file in question.
https://www.dropbox.com/s/z8emhnozgl00o09/05739abd-7bf3-4ced-873b-c57dfb72a68b?dl=0

**Comment by bloodmc** [comment]
@cartman-2000 This should be fixed. Please test latest build.

**Comment by bloodmc** [comment]
This is no longer a problem in latest build.
